BurntSushi/ripgrep

README.md
1) git is not a secure protocol and vulnerable to man-in-the-middle
attacks.
2) git:// is a pain for users behind proxy servers :(
Change-Id: I1901bebbaf8f64b23b070dee8732a6fb13cbdfdd
=> Prefer https:// over git://

src/types.rs
Not sure if there was a reason the r key was duplicated, if so I can revert that change.
=> Add a few more R relevant extensions

src/types.rs
**Use-case**
While not a vogue technology, VB is still commonly taught in many university settings and used in many commercial environments. Working with VB files out-of-the-box would thusly provide a lot of potential value to `ripgrep` users.
**Example**
I'm working on converting a legacy app to a modern infrastructure. The legacy app mixes CS and VB files liberally, so I always need to check both when doing command line string searches. For portability, it would be nice to just be able to ask for `-tcsharp -tvb` without registering with `--type-add` first.
**Tests**
I didn't notice any coverage aimed at this part of the code, but if I'm mistaken I'll amend the PR.
=> Add VB files to default type list

README.md, doc/rg.1, doc/rg.1.md, src/args.rs, src/gitignore.rs, src/ignore.rs, tests/tests.rs
But don't actually remove support for .rgignore until the next semver
bump.
Note that this puts us in line with the silver searcher:
https://github.com/ggreer/the_silver_searcher/pull/974
Fixes #40
=> Switch from .rgignore to .ignore.

src/types.rs
This pull request add the Swift filetype `*.swift` to the know filetypes of ripgrep
=> Add support for the Swift programming language file type

src/types.rs
Includes more commonly used extensions to the js type.
* coffe, used by coffescript
* ts, tsx, used by typescript
* jsx, used by react.js
* vue, used by vue.js
=> --type js: include more extensions

ci/script.sh, doc/rg.1, doc/rg.1.md, src/args.rs, src/search_buffer.rs, src/search_stream.rs, tests/tests.rs
Resolves #26 (or at least starts to).
=> Files with matches

src/main.rs
The main thread does directory traversal. Hence
number of threads = main Thread + number of worker threads.
We should have atleast one worker thread.
=> [Fixes #46] Use 1 less worker thread than number of threads

src/types.rs
(see https://github.com/clojure/clojurescript/wiki/Using-cljc)
=> Recognise cljc and cljx extensions as Clojure(script)

src/types.rs
Add type for hardware design and verification language SystemVerilog; known as SV in the industry.
=> Add SystemVerilog (SV) type

pkg/brew/ripgrep.rb
https://github.com/BurntSushi/ripgrep/commit/9fa38c62327b5e72111bc68b4c299fbf970d3f7c updated the package version in the Homebrew formula but didn't update the SHA256 hashes.
=> Update brew 0.2.1 package hashes

src/printer.rs
Relates to https://github.com/BurntSushi/ripgrep/issues/96 but actually paves the way to have it configurable in the future as per this enhancement: https://github.com/BurntSushi/ripgrep/issues/51
Could expand upon this to include attributes for each of the types of colours.
I've kept the spelling american for consistency.
=> Create Colour Choice struct to adjust colours depending on platform 

doc/rg.1.md, src/args.rs, tests/tests.rs
=> Max depth option

appveyor.yml
That will avoid all your future automatically deployed releases being described as "Windows release" when they contain binaries for Linux, OSX and Windows.
=> AppVeyor: Change release description to fit Travis binaries

HomebrewFormula, README.md, pkg/brew/ripgrep.rb
Because there have been several comments on the builds provided by @BurntSushi [having `simd-accel` enabled](https://github.com/BurntSushi/ripgrep/issues/10#issuecomment-250612979), vs [HomeBrew using rust stable to build](https://github.com/Homebrew/homebrew-core/pull/5268).  I thought I would create this PR to enable the BurntSushi/ripgrep repo to be used as a Homebrew tap.  This would allow those who are tracking these releases (built with rust nightly?) to have easy updates, at least until the official Homebrew build can enable `simd-accel`.
Another aside, this PR removes the non-64-bit releases from the `Formula`.  This is because everything Mac OS 10.7 and newer has to be running on an x86_64 cpu.  If you want to continue supporting non-64-bit installs, I can add it back to this PR.
=> Make the repo a Homebrew Tap

src/types.rs
.cmake is a common extension used by CMake modules and includes.
For example, the include macro searches for .cmake files - https://cmake.org/cmake/help/v3.5/command/include.html?highlight=include.
=> Added *.cmake extension to cmake file type.

README.md, pkg/brew/ripgrep-bin.rb
Since the homebrew-core formula was accepted, we should differentiate
the prebuilt formula available in this tap
Only after my previous PR was accepted (and I tried it again), did I notice that there may be an issue with conflicting formula names:
This is failing because the cache I have from installing the `homebrew-core` version of ripgrep doesn't match the sha of the prebuilt download.
=> Fix brew formula name to not conflict with core

src/types.rs
see #145.
I guess this is quite niche, it's just one templating language (although popular) but without the option for an override or extension locally I guess this is the best option.
=> add jinja type for *.jinja and *.jinja2

README.md
The `-Syu` flag will do a full system upgrade and then install the package, which is not necessarily the desired behavior. Only the `-S` flag is necessary to install a single package.
See https://wiki.archlinux.org/index.php/Pacman#Installing_specific_packages
https://wiki.archlinux.org/index.php/Pacman#Upgrading_packages
=> Change Arch Linux instructions

src/types.rs
`-tmarkdown` is somewhat lengthy and unwieldy in practice, we could easily use `-tmd` in addition for ease of access.
=> Adding extra .md filetype for ease of access to Markdown filetypes

src/args.rs, tests/tests.rs
Fixes #137.  I have no prior knowledge, but it looks like Args.walker() is the correct place to locate this...
Let me know if you think this should be documented anyplace.
=> Always follow symlinks on explicit file arguments

README.md
Since there seem to be a couple questions popping up concerning installation on Mac OS X.  I have updated the README with a clear(er?) delineation of Homebrew versions.
=> Update Homebrew instructions in the README

src/types.rs
Gradle is a build system for JVM-based languages that is configured via a Groovy DSL.
=> Add .gradle as a groovy extension pattern

README.md
Please note that the referenced copr repository should just be a temporary home while the Fedora/EPEL package review is pending.
https://bugzilla.redhat.com/show_bug.cgi?id=1380442
=> Add instructions for installation on Fedora 24+ and RHEL/CentOS 7.

README.md
In the `README.md` document, where said document documents the
availability of pre-built packages of ripgrep, document the
availability of such a package from the package management system Nix.
(@rolodato from #10: you may be interested, if you haven't already
noticed the package.)
=> Mention Nix package in README

src/types.rs
Like discussed in #196 
Filenames are the ones from oh-my-zsh (`*.zsh`) and the ones from here: https://www-s.acm.illinois.edu/workshops/zsh/startup_files.html
=> Add zsh type

src/types.rs
Cython a tool to compile python (or possibly 'pseudo' python i.e. python with a few type annotations thrown in) to down to C. Commonly, Cython files have the extension pyx (see https://en.wikipedia.org/wiki/Cython). Personally I think it makes sense to include these files in the python type filter. Cython is widely used in the scientific python community.
=> update python types to include Cython files

README.md
ripgrep is now in the main gentoo repo, courtesy of me. :smile:
=> Add Gentoo info to the README

ignore/src/types.rs
I remembered this article ["Rendering differences in prose documents"](https://help.github.com/articles/rendering-differences-in-prose-documents/). So I add filetypes refered in it. These filetypes can be previewed in Github.
- [Textile](https://github.com/textile) : a lightweight markup language that uses a text formatting syntax to convert plain text into structured HTML markup.
- [Org(Org Mode)](http://orgmode.org) : for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system
- [Rdoc](http://rdoc.sourceforge.net) : Documentation from Ruby Source Files
- [MediaWiki](https://www.mediawiki.org/wiki/Help:Formatting) : wiki markup used by [MediaWiki](https://www.mediawiki.org)
- [Pod](http://perldoc.perl.org/perlpod.html) …
=> Add textile, org, creole, rdoc, wiki filetype

Cargo.lock, Cargo.toml, ignore/Cargo.toml, ignore/examples/walk.rs, ignore/src/dir.rs, ignore/src/lib.rs, ignore/src/walk.rs, src/args.rs, src/main.rs, src/printer.rs, src/worker.rs
This adds a new walk type in the `ignore` crate, `WalkParallel`, which
provides a way for recursively iterating over a set of paths in parallel
while respecting various ignore rules.
The API is a bit strange, as a closure producing a closure isn't
something one often sees, but it does seem to work well.
This also allowed us to simplify much of the worker logic in ripgrep
proper, where MultiWorker is now gone.
=> Add parallel recursive directory iterator.

ignore/src/types.rs
While using ripgrep, I noticed that elixir wasn't one of the types included, so I added it into the types.rs.
=> Added elixir to types

src/args.rs, tests/tests.rs, tests/workdir.rs
This is a somewhat basic implementation of `-f-` (#7), with unit tests, just to start a discussion. Your suggestions are very welcome, of course!
Changes include:
1. The internals of the `pattern` function have been refactored to avoid code duplication, but there's a lot more we could do.  Right now we read the entire pattern list into a `Vec`.
2. There's now a `WorkDir::pipe` command that allows sending standard input to `rg` when testing.
Not yet implemented: aho-corasick, or any kind of sensible support for other extremely large inputs.
Thank you for helping me get this far, and for any further suggestions!
=> Allow specifying patterns with `-f FILE` and `-f-`

.travis.yml, Cargo.lock, Cargo.toml, build.rs, ci/before_deploy.sh, doc/rg.1, doc/rg.1.md, src/app.rs, src/args.rs, src/main.rs, src/search_stream.rs, src/unescape.rs, tests/tests.rs, tests/workdir.rs
There were two important reasons for the switch:
1. Performance. Docopt does poorly when the argv becomes large, which is
a reasonable common use case for search tools. (e.g., use with xargs)
2. Better failure modes. Clap knows a lot more about how a particular
argv might be invalid, and can therefore provide much clearer error
messages.
While both were important, (1) made it urgent.
Note that since Clap requires at least Rust 1.11, this will in turn
increase the minimum Rust version supported by ripgrep from Rust 1.9 to
Rust 1.11. It is therefore a breaking change, so the soonest release of
ripgrep with Clap will have to be 0.3.
There is also at least one subtle breaking change in real usage.
Previous to this commit, this used to work:
rg -e -foo
Where this would cause ripgrep to search …
=> Switch from Docopt to Clap.

doc/rg.1, doc/rg.1.md, src/app.rs, src/args.rs, src/search_buffer.rs, src/search_stream.rs, src/worker.rs, tests/tests.rs
Performs the opposite of `--files-with-matches`: only shows paths of files that contain zero matches.
Closes #138.
---
This is a rather quick-and-dirty patch: I had zero familiarity with the codebase, and I basically searched for `files.with.matches` to guide me where changes should be made. I've tried to match the overall code style, but I may have missed something.
=> Add --files-without-matches flag.

ignore/src/types.rs
Just noticed that Less and Sass are not supported by default. This PR adds types for both.
=> Less and Sass types

ignore/src/types.rs
Seems like #197 got lost in #202 
I added the missing `.zlogout`, and also search the ones without a leading `.` (which should be in `/etc`). Is there syntax for making a char optional (like `?` in regex)?
The entries are sorted in the order they're read by zsh, with the addition of a `*.zsh` at the end
=> Re-add zsh types

Cargo.lock
Brings in [this fix](https://github.com/kbknapp/clap-rs/issues/771).
=> Update Cargo.lock to bring in clap 2.19.2 fix for ZSH completions.

doc/rg.1, doc/rg.1.md, src/search_stream.rs
The first commit is an oversight I spotted immediately after having #239 accepted.
The second one is just a minor divergence between the documentation and the actual code ([`Args::threads()`](/BurntSushi/ripgrep/blob/851799f42be4409d4e2498960725e11d0514a0e7/src/args.rs#L667)). I'm assuming the code has the actual intended cap, as it's not too uncommon to find desktop machines with 12+ logical cores, it's still low enough not to accidentally overwhelm a modest (albeit modern) CPU, and it seems to be the more recent commit.
=> Minor code and doc fixes

ignore/src/types.rs
This PR adds support for two new file types:
* [Crystal](https://github.com/crystal-lang/crystal)
* [Kotlin](https://github.com/JetBrains/kotlin)
And adds a few common filename patterns to two existing file types:
* Perl
* Ruby
=> File types: add Crystal and Kotlin + expand Perl + Ruby

Cargo.lock, Cargo.toml, ignore/Cargo.toml, ignore/src/walk.rs, src/args.rs, src/atty.rs, src/main.rs
When running ripgrep like this:
rg foo > output
we must be careful not to search `output` since ripgrep is actively writing
to it. Searching it can cause massive blowups where the file grows without
bound.
While this is conceptually easy to fix (check the inode of the redirection
and the inode of the file you're about to search), there are a few problems
with it.
First, inodes are a Unix thing, so we need a Windows specific solution to
this as well. To resolve this concern, I created a new crate, `same-file`,
which provides a cross platform abstraction.
Second, stat'ing every file is costly. This is not avoidable on Windows,
but on Unix, we can get the inode number directly from directory traversal.
However, this information wasn't exposed, but now it is (through both the
ignore and …
=> Don't search stdout redirected file.

ignore/src/types.rs
.eex is the default file ending for templates using Elixir's template engine EEx.
=> File Types: Add .eex under Elixir

ignore/src/gitignore.rs
The documentation says:
> If `$XDG_CONFIG_HOME` is not set or is empty, then
> `$HOME/.config/git/ignore` is used instead.
This is the expected behavior, but the code looked at ~/git/ignore
instead.
This is my first Rust code, so it might be wrong..!
=> Look for global git/ignore in ~/.config/git, not ~/git

ignore/src/types.rs
Kind of self explanatory, for some reason `.sass` itself was missed from the sass type. I guess because `sass` is nowadays slightly less popular than `scss` but still very much in use.
=> add '*.sass' to sass type

src/args.rs, termcolor/README.md, termcolor/src/lib.rs
Pursuant to the discussion in #324. The new implementation breaks the `termcolor` API by renaming the `Stdout` type to `StandardStream`, which now has two constructors `stdout()` and `stderr()` rather than a single `new()`. `StdoutLock` is changed analogously.
Implementation was very straightforward.
=> Make it possible for termcolor to write to stderr (take 2)

globset/src/glob.rs
Implement `Hash` for `Glob`, and re-implement `PartialEq` using only non-redundant struct fields.
I've been using the globset crate as a library (thank you!), and ran across the fact that `Glob` was un-hashable while deduping user inputs.
=> Implement Hash for Glob

README.md
Also document that ctrl-c doesn't restore the termcolor (#347).
=> Add "Known issues" section in README.md

Cargo.lock, Cargo.toml, README.md, doc/rg.1.md, src/app.rs, src/args.rs, src/decoder.rs, src/main.rs, src/worker.rs, tests/tests.rs
Add support for additional text encodings.
This includes, but is not limited to, UTF-16, latin-1, GBK, EUC-JP
and Shift_JIS. (Courtesy of the `encoding_rs` crate.)
Specifically, this feature enables ripgrep to search files that are
encoded in an encoding other than UTF-8. The list of available encodings
is tied directly to what the `encoding_rs` crate supports, which is in
turn tied to the Encoding Standard. The full list of available encodings
can be found here: https://encoding.spec.whatwg.org/#concept-encoding-get
This pull request also introduces the notion that text encodings can be
automatically detected on a best effort basis. Currently, the only
support for this is checking for a UTF-16 bom. In all other cases, a
text encoding of `auto` (the default) implies a UTF-8 or ASCII …
=> Add support for additional text encodings.

doc/rg.1.md, src/app.rs, src/args.rs, src/printer.rs, tests/tests.rs
This permits setting the maximum line width with respect to the number
of bytes in a line. Omitted lines (whether part of a match, replacement
or context) are replaced with a message stating that the line was
elided.
Fixes #129
=> Add new -M/--max-columns option.

appveyor.yml
Use a `ps:` (powershell) command to copy the completions file so that we
can use directory globbing to find the file.
=> Add powershell completions to build artifacts

src/printer.rs, tests/tests.rs
I added coloring for columns and separators. Also I fixed some bugs, when paths in context were not colored.
=> Improves Printer, adds ColorSpecs for column and separator

Cargo.lock, Cargo.toml, build.rs, src/app.rs, src/args.rs
~~**DO NOT MERGE - until clap v2.23.1 is on crates.io**~~
It's safe to merge now.
This commit updates clap to v2.23.1
The update contained a bug fix in clap that results in broken code in
ripgrep. ripgrep was unknowingly relying on the bug, but this commit fixes that
issue. The bug centered around not being able to override the
auto-generated help message by supplying a flag with a long of `help`.
Normally, supplying a flag with a long of `help` means whenever the user
passes `--help`, the consuming code (e.g. ripgrep) is responsible for
displaying the help message. However, due to the bug in clap this wasn't
necessary for ripgrep to do unless the user passed `-h`. With the bug
fixed, it meant the user passing `--help` and clap expected ripgrep to
display the help, yet ripgrep expected …
=> updates clap and removes home rolled -h/--help distinction

src/printer.rs, tests/tests.rs
Fixes #451 
```
~/ripgrep$ cat tests/digits.txt 
1 2 3
123
~/ripgrep$ cargo run -- "\d" tests/digits.txt -o --column
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Running `target/debug/rg '\d' tests/digits.txt -o --column`
1:1:1
1:3:2
1:5:3
2:1:1
2:2:2
2:3:3
~/ripgrep$ cargo run -- "\d+" tests/digits.txt -o --column
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Running `target/debug/rg '\d+' tests/digits.txt -o --column`
1:1:1
1:3:2
1:5:3
2:1:123
```
=> Fix reiteration of the first found match with --only-mathing flag

.gitignore, snapcraft.yaml
[Snapcraft](https://snapcraft.io/) makes Linux packaging very simple in a cross-distro
way. This adds the snapcraft.yaml file to setup a snap of ripgrep
=> Add snapcraft.yaml

src/main.rs, tests/tests.rs
Fixes #483.
Self-explanatory, but example behavior as follows (in ripgrep base directory).
```
$ (issue-483) cargo run -- --quiet --files --glob '*.tom'; echo "$?" 
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Running `target/debug/rg --quiet --files --glob '*.tom'`
1
$ (issue-483) cargo run -- --quiet --files --glob '*.toml'; echo "$?" 
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Running `target/debug/rg --quiet --files --glob '*.toml'`
0
```
=> Make --quiet flag apply when using --files option

src/args.rs
With vim configured with:
set grepprg=rg\ --vimgrep
set grepformat^=%f:%l:%c:%m
and running the command `:grep 'vimgrep' doc/rg.1`, the output should be:
doc/rg.1:446:8:.B \-\-vimgrep
but the actual output was:
446:8:.B \-\-vimgrep
Same issue would happen if results only match one file. Ag behaves as expected.
=> Should show filename for one file with vimgrep

doc/rg.1, doc/rg.1.md, src/app.rs
In `src/app.rs`, change typo "When ansi used" to "When ansi is used".
Update man pages with missing `ansi` option for `--color`.
=> Update documentation for --color ansi

src/args.rs
It's usage was replaced by the `color_choice` function. Also, `color` was outdated, as it didn't include testing for the new "ansi" option.
=> Remove vestigial color function from src/args.rs

doc/rg.1, doc/rg.1.md, src/app.rs
Formatting of rg.1.md. Removed backticks from already indented code.  Added missing italic to some arguments, Replaced -n by --line-number in --pretty for better clarity. Added explicit example of `*.foo` instead of `<glob>` in examples. Added vim information to --vimgrep.
In src/app.rs, also changed help text for pattern and regexp. Actually, "multiple patterns may be given" was not true for the standalone pattern.
=> Update help and man pages

doc/rg.1, doc/rg.1.md, src/app.rs, src/args.rs
This reverts a couple of changes introduced in 4c78ca8
@BurntSushi, not sure if you want to merge this. Just trying to revert some changes I introduced, plus keeping the `PATTERN` argument consistently uppercased, so error messages can look like
```
error: The following required arguments were not provided:
<PATTERN>
```
=> Use uppercase for required argument names

ignore/src/types.rs
This change consists of two commits:
- Add a new fietype grouping for "msbuild" related files.
- Add .inl files to be included in the cpp filetype grouping.
=> Add "msbuild" filetype grouping, and add .inl files to the "cpp" grouping. 

src/args.rs, tests/tests.rs
fixes BurntSushi/ripgrep#506. Word boundary search as arg had unexpected
behavior. added non-capturing capture group to regex to encapsulate 'or' option search and
prevent expansion and partial boundary finds.
Signed-off-by: Evan.Mattiza <emattiza@gmail.com>
=> fix word boundary w/ capture group

wincolor/src/win.rs
The primary motivation for this commit was rust-lang/cargo#4189 where dropping a
`wincolor::Console` would call `CloseHandle` to close the console handle. Cargo
creates a few `Console` instances so it ended up closing stdout a little
earlier as intended!
The `GetStdHandle` function returns handles I believe aren't intended to be
closed (as there's no refcounting). I believe libstd doesn't close these
handles.
This commit also moves to calling `GetStdHandle` on demand which libstd changed
to doing so recently as well, preventing caching of stale handles that change
over time with calls to `SetStdHandle`.
=> wincolor: Re-fetch the console on all calls

complete/_rg
This change is related to #532, though the actual problem there had already been fixed by the earlier addition of the hand-written completion function. In going over that function i found several issues/limitations which i've corrected:
* Added missing options (most notably `-o`)
* Fixed the confusion between `--count` and `--max-count`
* Improved the consistency of the wording — The previous descriptions had mixed usage of capitalisation, punctuation, contractions, &c., some of them were copied from the `--help` output verbatim, and so on
* Added completion for encodings — I didn't want to include a gigantic list of every single individual encoding, so i compressed them all into a few lines by making use of brace expansion. As i noted in the code, it's *super* hard to read this way, but …
=> Improve zsh completion function

ci/script.sh, ci/test_complete.sh, complete/_rg
Per our discussion in #536: Here's something to hopefully prevent the zsh completion function from getting out-of-synch with the actual app.
I used a slightly different strategy from the one i mentioned before, but it's the same basic idea — pull all of the options out of the `--help` output, pull all of the options out of the completion function, compare the two. I tried to address your concerns about false positives/negatives as best i could; i've documented the assumptions i make in the script, and i think it should be OK as long as nobody does anything bizarre.
I've tested this in `dash`, `bash`, and `zsh`. It also works in `ksh93` if you make `local` an alias for `typeset`... but you use `local` in your other scripts so i assume `ksh` compatibility isn't a big concern.
Anyway, it …
=> Add test script to compare `rg --help` output to zsh completion function

src/app.rs
#524 sounded fun and easy. I only just barely know what i'm doing in Rust though — is this a reasonable way to go about this? I don't think the method will scale elegantly beyond three or four features, but i figured something fancier could quickly be devised if it came to that in the future.
This is the sort of output you get (i don't have Rust nightly so i added a dummy option to test; it's not present in the actual commit of course):
```
heartswap:ripgrep % cargo build -q --release --features 'foo'
heartswap:ripgrep % target/release/rg --version
ripgrep 0.5.2, with features (+/-): +foo -avx-accel -simd-accel
```
=> Update `--version` output to show compile-time features

src/app.rs
This reuses the systemd convention of putting flags on a separate line.
All credit to okdana for the implementation.  Addresses #524.
=> Tweak long_version features output

README.md
I switched Fedora usernames, so new builds will be at a different URL.
=> update COPR name

ignore/src/gitignore.rs, ignore/tests/gitignore_matched_path_or_any_parents_tests.rs
In `matched_path_or_any_parents()` implementation, we missed the point
that when we start walking up the tree, we have to set `is_dir` to
`true`, so path `ROOT/a/b/c` matches pattern `/a/`, although the
original path is not a dir.
=> [ignore] Fix matched_path_or_any_parents() for patterns ending in slash

src/args.rs, src/printer.rs
Fix for https://github.com/BurntSushi/ripgrep/issues/342
Root cause is that the standard Windows PowerShell launch shortcut sets the console background color to "dark magenta", then re-defines "dark magenta" as RGB(1, 36, 86) aka "powershell noble blue." Thus if a console app writes output with "dark magenta" foreground color, it will be invisible in a default PowerShell console.
Fix is to do a simple, Windows-only check for a "dark magenta" background at startup, and in this case change path output style to "intense magenta," which will render fine.
Result:
Potential concerns:
- Arg parsing now has to know about Windows console. That's not great but it was simplest path forward for me as a rust n00b.
- This will add "intense" styling to path output even when user has manually overridden …
=> Fix invisible file path text in PowerShell

ci/test_complete.sh, complete/_rg
Hey again! I've been collecting issues left over from my previous effort and i think i've found as many as i can for now.
The biggest problem, which was carried over from the original, was that option completion was basically broken on zsh 5.1 (the latest version available in Ubuntu Xenial). But i also found some typos in option names, missing actions for options that take arguments, missing exclusion rules, &c.
In addition to fixing bugs i improved the `colorspec` handling slightly, and i added completion for sequences of types when given `--type-add <type>:include:`. And i re-ordered the options to match the `--help` output like i mentioned wanting to do before.
I tested this on zsh 5.1, zsh 5.2, and zsh 5.3 and it seems OK. Really hard to test properly though, so i'm sure i'll find …
=> Refactor completion function

README.md
change the profile showing command to one that matches the microsoft article linked, as its simpler and the old one didn't work at least on windows 10 creators edition.
=> fix profile showing command for powershell

.travis.yml, ci/test_complete.sh, complete/_rg
Sorry for PR spam, found another issue with this. :/
I hadn't noticed that the old completion function didn't support completing values without a space after short options — doing something like `rg -C3 <tab>` instead of `rg -C 3 <tab>` would break the completion.
I fixed that. And, as discussed last time, i updated the test stuff so that it just pulls the optspecs straight out of the function. That should make the 'parsing' a lot more reliable (at the expense of requiring zsh for the test, obv).
Not sure if i put the zsh-installation stuff in the right place, guess we'll see what it says...
=> zsh completion... again

Cargo.lock, Cargo.toml, src/main.rs
I was just having a quick look at the code and realised that you were depending on `libc` but not using it anywhere, so I removed the dependency. The effect on the benchmarks is still yet to be seen.
=> Remove unused libc dependency

complete/_rg, doc/convert-to-man, doc/rg.1, doc/rg.1.md, src/app.rs, src/args.rs, tests/tests.rs
Let's try this!
This PR adds `-x`/`--line-regexp`, which essentially wraps the pattern in `^`...`$` in order to make it match whole lines only. This is an option defined in the [POSIX spec](http://pubs.opengroup.org/onlinepubs/009695399/utilities/grep.html) for `grep`, and one that i use a lot. I found it rather frustrating that `ag` didn't have it.
I will add additional notes as comments on the diff.
=> Add -x/--line-regexp

Cargo.lock, Cargo.toml
If the core functionality uses SIMD, no reason not to use it for the encoding stuff, too.
=> Pass the simd-accel feature to encoding_rs

ignore/src/types.rs
Yocto -> BitBake: because `bitbake` is just one tool of the many tools that the `Yocto` project has and these files are specific to it.
GNUmakefile: the `make` tool is case-sensitive on this one
*.prf: is basically the equivalent of `*.pri`, just that one is included through `include(file)`(where you have `file.pri`) and another is included through `CONFIG += file`(where you have `file.prf` usually in `mkspecs`).
=> Types extension and Yocto renaming to BitBake

ignore/src/walk.rs
This function doesn't say it's enabled by default, but it looks like it is, based on my reading of `dir.rs`: https://github.com/BurntSushi/ripgrep/blob/30608f2444a2abc7aae8e7b96cd5cff4f98bfe71/ignore/src/dir.rs#L429-L435
=> ignore: document git_global enabled by default

termcolor/src/lib.rs
This commit Fixes a bug where the `StandardStream` type isn't `Send` on
Windows. This can cause some surprising compile breakage, and the only
motivation for it being non-Send was dubious. Namely, it was a result of
trying to eliminate code duplication.
This refactoring also eliminates at least one "unreachable" panic case
that was a result of trying to eliminate code reuse, so that's a nice
benefit as well.
=> termcolor: make StandardStream be Send

Cargo.lock, Cargo.toml, src/main.rs
See https://github.com/BurntSushi/ripgrep/issues/200.
This is a Unix-only workaround, until the larger refactoring mentioned in that issue is done. I'm not sure what our current behavior is on Windows, but this should't change it in any case. Are there any cases where rg has side effects, where a sudden termination like this might not be a good idea?
=> restore the default SIGPIPE behavior as a temporary workaround

Cargo.lock, Cargo.toml
This is a performance improvement. The theoretically breaking changes (removal of a cargo feature and removal of `Encoding::for_name()`) don't affect ripgrep.
=> Update encoding_rs to 0.7.0

ignore/src/types.rs
Simply adds a file type filter for [Elm](elm-lang.org/).
=> Add Elm file type

ignore/src/walk.rs
Adds a single function to toggle all the enabled-by-default options on `WalkBuilder`. I implemented this for [my crate](https://github.com/haptics-nri/bible-extractor/blob/76769934d69c6cd9857884e91e30eb2f6370973a/src/main.rs#L98) because I wanted a parallel directory iterator but I don't actually need the fancy ignore stuff. Feel free to reject if that isn't an intended use case.
=> ignore: add grouped defaults toggle

src/main.rs
Fixes #600
Stacktraces show that this check is the culprit. Listing all files in my test folder with 235k files on Windows now takes about 4.2 seconds. It didn't finish before I canceled before that when MsMpEng.exe kicked in.
The stacktrace:
/cc @BurntSushi @roblourens
=> Avoid expensive check with --files

src/printer.rs
=> Color --replace text using the match type

README.md
Notify user cargo install ripgrep contains debug symbols and informs how to stripe them.
Fix #595
=> Add message to README to inform about `cargo install ripgrep` not being `strip`ed

globset/README.md
The version number in globset's README is slightly behind the published version.
(I just used the GitHub editor; this isn't tested or anything)
=> globset README version bump

ignore/src/types.rs
I think this covers most usecases i.e: `Dockerfile.blah` and `blah.Dockerfile`
=> Add support for Dockerfiles filtering

src/search_stream.rs
Print the context if there's a context left to be printed after returning early from a search (because of `--max-count`).
Fixes #402.
=> Fix printing context after an early return from a search

ignore/src/types.rs
Purescript is a functional language that compiles to javascript (https://github.com/purescript/purescript)
=> Add purescript to built-in types

tests/tests.rs, tests/workdir.rs
APFS does not support creating filenames with invalid UTF-8 byte codes,
thus this test doesn't make sense. Skip it on file systems where this
shouldn't be possible.
Fixes #559
=> Skip regression 210 test on APFS

ignore/src/gitignore.rs
When processing a rule that ends in a slash, we strip it off and set the
`is_only_dir` flag.  We then apply the rule that paths that aren't
absolute should be given an implicit `**/` prefix, while avoiding
adding that prefix if it already exists.
However, this means that we miss the case in which we had already
stripped off the trailing slash and set `is_only_dir`.  Correct this
by also explicitly checking for that case.
Fixes #649
=> Properly match the rules "**/" and "!**/"

ignore/src/types.rs
Simply adds a file type filter for [Protocol Buffers](https://developers.google.com/protocol-buffers/).
=> Add Protocol Buffer file type

ignore/README.md
Small thing; I noticed a discrepancy between the released version and documented.
=> Bump Cargo.toml version in Ignore's ReadMe.md from 0.2 to 0.3

globset/src/glob.rs
Fixes #663.
I hope this is the idiomatic way to do this. Seems to work at least:
```
% ls
abc  bbc  cbc  dbc
% \rg -u --files -g '[!ab]bc'
cbc
dbc
% \rg -u --files -g '[^ab]bc'
abc
bbc
% rg-dev -u --files -g '[!ab]bc'
cbc
dbc
% rg-dev -u --files -g '[^ab]bc'
cbc
dbc
```
For the tests i just duplicated a bunch of the ones that were there for `[!...]` 🤷‍♀️
=> Support both [^...] and [!...] for globset class negation

ignore/src/types.rs
This PR adds Jupyter notebook file extensions (`.ipynb`/`.jpynb`) to the type list. 
Some context: Notebooks are widely used in the scientific computing world. Under-the-hood are json files that are a bit unwieldy (understatement) to look at when printed to the command line. 
I used the `nb` key for notebook, but am happy to change it if that is preferred.
=> add notebook file extensions to types

src/args.rs, tests/tests.rs
Fixes #693.
When `rg` has been placed in a 'contextless mode' by the use of `--count`, `--files-with-matches`, or `--files-without-match`, it should omit the context separator even if given a context option like `-A` or `-C`. This matches how (e.g.) `grep` behaves.
Before:
```
% \rg -cC1 context.separator
complete/_rg:1
--
doc/rg.1.md:1
--
src/app.rs:3
--
src/printer.rs:9
--
src/args.rs:7
```
After:
```
% target/release/rg -cC1 context.separator
complete/_rg:1
doc/rg.1.md:1
src/app.rs:3
src/args.rs:7
src/printer.rs:9
```
=> Omit context separators when using a contextless option like -c or -l

.travis.yml, ci/before_deploy.sh, ci/install.sh, ci/script.sh, ci/utils.sh
The purpose of this is so that `ripgrep` will create the "release" binary for the most popular ARM target - but I did not manage to test if the binary is correctly pushed to the "releases" page...
=> Add armhf build to Travis CI

doc/rg.1, doc/rg.1.md, grep/src/search.rs
Fixes #717 (partially)
As suggested, i changed the smart-case feature in the `grep` crate to look for upper-case characters in the pattern itself rather than the AST. I also added some tests for it, and a note in the manual.
I didn't update the `grep` version number — you don't want me to do that, right?
=> Improve smartness of --smart-case

.travis.yml, Cargo.lock, Cargo.toml, ignore/Cargo.toml, wincolor/Cargo.toml, wincolor/src/lib.rs, wincolor/src/win.rs
This PR updates all dependencies to their latest versions, including clap, which bumps the minimum Rust version required by ripgrep to Rust 1.20.0. We've also removed the dependency on winapi 0.2 in every case but one (the `memmap` crate). Once `memmap` is updated to use winapi 0.3, ripgrep should no longer need 0.2.
This also rolls in #699 and #722.
=> dependency updates

complete/_rg, doc/rg.1, doc/rg.1.md, src/app.rs, src/args.rs, src/printer.rs, tests/tests.rs
As per the discussion on #544, this is my initial attempt at adding support for fixed width line numbers. Please review and let me know if things can be improved upon.
A few thoughts I had as I worked on this:
- Rust's `format!` macro currently has no way of providing a custom padding character as a parameter. You have to provide it directly in the format string itself. (As per [this](https://doc.rust-lang.org/std/fmt/#syntax), only the width can be provided as a parameter.)
- This meant that adding support for format strings as suggested in the issue discussion proved to be difficult. Right now, the argument only accepts a number. It seems that we'll have to write a custom code for left padding or rely on a library to achieve this. I'm open to suggestions on this one.
- Should we handle …
=> Add support for fixed width line number display (fixes #544)

globset/README.md, globset/src/glob.rs, globset/src/lib.rs, grep/src/nonl.rs, grep/src/search.rs, ignore/src/gitignore.rs, ignore/src/overrides.rs, ignore/src/types.rs, ignore/src/walk.rs, src/args.rs, src/decoder.rs, src/printer.rs, src/search_stream.rs, src/worker.rs, termcolor/README.md, termcolor/src/lib.rs
So as I was learning and going through the codebase, I came across `try!` a lot. Thinking it was a new macro/syntax I had to learn, I searched the Internet for it only to [learn](https://doc.rust-lang.org/std/macro.try.html) that it was an earlier alternative to the newer `?` operator, which should be preferred nowadays.
As a result of this, I have changed all usages of the `try!` macro to the newer `?` operator in the codebase.
My reasoning is as follows:
- The latest edition (2nd) of the Rust Programming language book teaches newcomers about the `?` as the shortcut for [propagating errors](https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-).
- I also find that `?` is easier to parse and read than `try!` and is …
=> Replace all usages of try! macro with the ? operator

src/args.rs, tests/tests.rs
This is the most straightforward fix I could think of for #709. Please let me know if it could be improved upon.
Thanks!
=> Suggest --fixed-strings flag in case of regex parse error (closes #709)

Cargo.lock
Crossbeam 0.3.0 uses the old auto trait syntax and 0.3.2 switched to the new one. Ripgrep is a part of Rust's test suite and, since it depends on crossbeam 0.3.0, it is currently blocking the following PR, which removes the old auto trait syntax in favor of the new one: https://github.com/rust-lang/rust/pull/46480#issuecomment-355735400
Diff between versions 0.3.0 and 0.3.2: https://github.com/crossbeam-rs/crossbeam/compare/v0.3.0...v0.3.2
=> Update crossbeam to 0.3.2

ignore/src/types.rs
[Apache Avro](http://avro.apache.org/) uses `.avsc`, `.avpr` & sometimes `.avdl` (json-like) formats to store Kafka schema information. Adding them to rg because I hated adding `--type-add` to all my searches. Thanks :)
=> Adding types for Kafka schema

README.md
References: https://bodhi.fedoraproject.org/updates/FEDORA-2018-ca3c304458
---
P.S. update is still not pushed, but should be fully available within few days
=> readme: ripgrep is in Fedora 27

README.md
I added documentation for Ubuntu users who want to install `ripgrep` using the snap tool
=> Add Ubuntu installation guide to README

ignore/src/types.rs
Hi there!
This adds adds support for webidl files `.idl` and `.widl`.
=> Add webidl file type support

ignore/src/types.rs
.hxx is commonly used as a header extension for C++ files, since .cxx was already added, I was free to add the header extension to match the implementation file.
=> Add *.hxx to the cpp filetype

ignore/src/types.rs
GN is Googles new build system, originally developed to build chromium. They use the *.gn and *.gni file endings.
=> Add GN as new filetype

ignore/src/gitignore.rs, ignore/src/overrides.rs, ignore/tests/gitignore_matched_path_or_any_parents_tests.rs
Fixes #761
This is kind of a scary change, but it *seems* right...?
Per the unit tests, the `ignore` crate assumes that `bar/*.rs` should match both `bar/main.rs` and `foo/bar/main.rs`. However, the `gitignore` documentation seems to state very clearly that it should *not* behave this way:
>Otherwise [if the pattern contains a slash], Git treats the pattern as a shell glob suitable for consumption by fnmatch(3) with the FNM_PATHNAME flag: wildcards in the pattern will not match a / in the pathname. **For example, "Documentation/*.html" matches "Documentation/git.html" but not "Documentation/ppc/ppc.html" or "tools/perf/Documentation/perf.html".**
The real-world behaviour of git 2.16.1 is consistent with this.
Looking at the `ignore` unit tests, the test patterns borrowed from …
=> Make handling of patterns containing a `/` match actual git behaviour

termcolor/src/lib.rs, tests/tests.rs
AppVeyor CI supports coloring the console through ANSI escape codes, however its support is incomplete (appveyor/ci#1824). One particular issue is that `\x1b[m` is not recognized as the same as `\x1b[0m`. 
This caused colored output using this library extremely ugly on AppVeyor as the color is never reset ([example](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6004/job/a23aftwu88yh35c4), start from line 675).
While technically an AppVeyor bug, I think changing the code here would improve compatibility anyway. (That issue is also untouched for 2 months so I doubt if AppVeyor is going to fix it soon.)
=> termcolor: Write `Ansi::reset()` using `\x1b[0m` instead of `\x1b[m`

ignore/src/dir.rs, ignore/src/walk.rs, src/args.rs
This allows for application specific ignorefile names, e.g. using
`.fdignore` for `fd`.
- Moved the hardcoded `.rgignore` from the ignore crate to ripgrep
- `.ignore` is always respected and has the highest precedence
=> Support ignore files with custom names

src/app.rs, termcolor/src/lib.rs
This commit adds 256-color and 24-bit truecolor support to ripgrep.
This only provides output support on ANSI terminals. If the Windows
console is used for coloring, then 256-color and 24-bit color settings
are ignored.
This PR is based on #452. In the interest of getting it merged, I did a bit of cleanup.  Namely, on Windows, unsupported colors are just ignored instead of falling back to white. I also improved the error reporting when attempting to parse RGB/256-color settings.
I did manual QA on Windows and Linux and everything seems to be working as I'd expect! Thanks @tiehuis!
=> termcolor: add extended color support

Cargo.lock, Cargo.toml
This incorporates the simplification @Veedrac made, because rustc apparently changed codegen. It does *not* include any additional dependencies.
=> update bytecount to improve perf with current rustc

Cargo.lock, Cargo.toml, README.md, build.rs, complete/_rg, doc/rg.1, doc/rg.1.md, globset/Cargo.toml, grep/Cargo.toml, ignore/Cargo.toml, src/app.rs, src/args.rs, src/config.rs, src/logger.rs, src/main.rs, tests/tests.rs, tests/workdir.rs
This PR fixes both #196 and #553. The commit messages have most of the details (including some goodies like a 2x decrease in release build time), but the TL;DR is that ripgrep now recognizes a `RIPGREP_CONFIG_PATH` environment variable. When set and non-empty, ripgrep will read shell arguments from it (one per line) and prepend them to whatever explicit CLI arguments have been given. A new flag, `--no-config`, prevents any sort of configuration from being loaded from a file.
This does not add any support for auto-loading config files from pre-determined locations like one's `$XDG_CONFIG_HOME` directory. [It was decided](https://github.com/BurntSushi/ripgrep/issues/196#issuecomment-362850321) to punt on that for now, and one wonders how far we can get with just the env var approach!
=> add support for persistent config

src/app.rs
Found this while testing kbknapp/clap-rs#868
=> fixes a PATTERN->pattern typo in argument conflicts

.gitignore, .travis.yml, Cargo.toml, FAQ.md, GUIDE.md, README.md, build.rs, ci/before_deploy.sh, ci/install.sh, ci/script.sh, ci/utils.sh, compile, doc/rg.1.txt.tpl, src/app.rs
This PR overhauls ripgrep's prose documentation. We re-organize the README and split parts of it out in a user guide and a FAQ.
=> revamp documentation

ignore/src/types.rs
VHDL is a very popular language for hardware design for FPGA etc. I think this would be useful for others :-)
=> ignore: add support for VHDL type

ignore/src/dir.rs, ignore/src/walk.rs
This change ensures that `add_custom_ignore_filename` works even if all other ignore rules are disabled, see #800.
I'm not whether it is a good idea to adapt the existing unit test (or if I should have added another unit test).
=> Allow custom ignore files to be used exclusively

FAQ.md, complete/_rg, src/app.rs, src/printer.rs, termcolor/src/lib.rs, tests/tests.rs
Closes #798 
This PR implements underline support in `termcolor`. Hopefully I've done it right because it seemed straightforward enough to implement. 😄
I tested this by doing `./target/release/rg 'bufwtr' --colors 'match:style:underline'` on my PC after building `rg`, and I was able to see underlined text.
=> Implement underline support in termcolor (closes #798)

termcolor/src/lib.rs
I went through the code (and searched the WWW) to understand what the `intense` parameter does in `termcolor`. Hopefully I've captured the intent behind them to the best of my understanding.
=> Add termcolor docs explaining what intense does (closes #797)

termcolor/src/lib.rs
Just noticed this while writing a ?Sized bound when using termcolor.
=> Add ?Sized bound to WriterColor for &'a mut T

Cargo.lock, ignore/src/walk.rs
This commit fixes a performance regression in Windows that resulted from
fallout from fixing #705. In particular, we introduced an additional
stat call for every single directory entry, which can be quite
disastrous for performance.
There is a corresponding companion PR that fixes the same bug in
walkdir: https://github.com/BurntSushi/walkdir/pull/96
Fixes #820
=> ignore: fix performance regression on Windows

.travis.yml, GUIDE.md, build.rs, ci/script.sh
This PR fixes a few miscellaneous bugs: #789 (omit revision in version string when unavailable), #791 (add man page to ARM build) and #815 (clarify ripgrep failure mode in user guide).
=> miscellaneous fixes

README.md
Prefix burntsushi/ripgrep/ is not needed, ripgrep-bin works fine :)
=> Shorten Rust Nightly brew install command

README.md
In the snap store, ripgrep 0.8.1 is only available as a candidate release, while the default (stable) release is 0.7.1.
=> Added instructions for installing latest release with snap

README.md
Scoop, a popular Windows package manager, lists and regularly updates ripgrep. Would be useful to add instructions.
=> Add scoop install instructions

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, appveyor.yml, ci/before_deploy.sh, globset/Cargo.toml, grep/Cargo.toml, ignore/Cargo.toml, src/args.rs
Pretty much what it says on the tin. This also brings in new AVX2 optimizations added in the regex crate. See: https://github.com/rust-lang/regex/pull/456
We also employ the totally novel idea of updating the CHANGELOG incrementally, instead of doing everything in one swoop during a release.
Note that this does not move to `regex-syntax 0.5.0` yet. That requires a bit more work.
=> update regex to 0.2.9, enables portable binary releases

Cargo.lock, Cargo.toml
Currently, builds with `simd` and `avx` features are failing due to mismatches in latest `std::arch`. This PR updates the version of `regex` to sync with latest marco in `std::arch`, `is_x86_feature_detected!`. https://github.com/rust-lang/regex/commit/c84bc41e5aceb87b6a5fa3d4b75ca85c1b1fd6f6
=> Update `regex` version to match changes in std::arch

termcolor/src/lib.rs
There is an issue with the Windows 10 console where if you issue the bold
escape sequence after one of the extended foreground colors, it overrides the
color.  This happens in termcolor if you have bold, intense, and color set.
The workaround is to issue the bold sequence before the color.
This is for rust-lang/rust#49322.
=> Fix bold, intense color on Windows 10 console.

globset/src/lib.rs, ignore/src/gitignore.rs
The clone instance for GitignoreBuilder is useful when building a gitignore line-by-line from user input, checking that they match some file as they are added. GitignoreBuilder and GlobsetBuilder look plain enough to have a clone instance.
=> Add Clone / Debug instance for GitignoreBuilder and GlobsetBuilder

Cargo.lock, Cargo.toml, ignore/src/lib.rs, ignore/src/walk.rs
There is a small hiccup here in that a `DirEntry` can embed errors
associated with reading an ignore file, which can be accessed and logged
by consumers if desired. That error type can contain an io::Error, which
isn't cloneable. We therefore implement Clone on our library's error
type in a way that re-creates the I/O error as best as possible.
Fixes #891
=> ignore: impl Clone for DirEntry

ignore/src/types.rs
This adds a verilog type (.v & .vh).
This also includes the typical SystemVerilog extensions (.sv & .svh).
System Verilog is an extension to Verilog, but I think you can combine both in one rg type.
=> Added verilog type

CHANGELOG.md, globset/src/lib.rs, ignore/src/dir.rs, ignore/src/gitignore.rs
This commit makes Gitignore::empty a bit faster by avoiding allocation
and manually specializing the implementation instead of routing it through
the GitignoreBuilder.
This helps improve uses of ripgrep that traverse *many* directories, and
in particular, when the use of ignores is disabled via command line
switches.
Fixes #835, Closes #836
=> ignore: speed up Gitignore::empty

ignore/src/types.rs
"haskell" is a bit long to type and I think most people will intuitively try "-ths", like "-tpy".
=> Add a shorthand file type "hs" for Haskell

ignore/src/gitignore.rs, ignore/src/overrides.rs
A small documentation update for `OverrideBuilder` and `GitignoreBuilder`.
Closes #910
=> Documentation Update

Cargo.lock, Cargo.toml, globset/Cargo.toml, grep/Cargo.toml, ignore/Cargo.toml
I left the simd-accel feature in globset to avoid the breaking change. Not sure if this was the right thing to do ;)
=> Update regex to 1.0 and run a full cargo update

README.md
I just saw the recent addition of BSD installation instructions to the README file. So I thought, what the heck, why not add installation instructions for Macports as well?  :smiley:
This is a tiny change, so I think it should be okay to merge.
=> Add MacPorts installation instructions to README

ignore/src/types.rs
Add the following file types to the built-in type list:
- Android AIDL files (*.aidl)
- Android platform makefiles (*.mk, *.bp)
Note: I went with "amake" as the name for the Android makefile pattern because it's quick to write. One could argue that something like "android-make" is easier to comprehend when skimming through the output of --type-list.
=> ignore/types: add support for a few Android platform file types

src/main.rs, tests/tests.rs, tests/workdir.rs
Exit code `1` was shared to indicate both "no results" and "error." Use status code `2` to indicate errors, similar to grep's behavior.
Fixes #948
Adds integration tests for exit codes.
Adds test helper `WorkDir::assert_exit_code(&self, expected_code: i32, cmd: &mut process::Command)` to match arbitrary exit codes in tests.
```sh
cargo test exit_code
```
Verify that the exit code is now `2` for error:
```
$ cargo run -- '*' src/main.rs ; echo "Status code: $?"
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Running `target/debug/rg '*' src/main.rs`
regex parse error:
*
^
error: repetition operator missing expression
Status code: 2
```
And remains `0` when matches are found:
```
$ cargo run -- 'main' src/main.rs ; echo "Status code: $?"
Finished dev [unoptimized + debuginfo] …
```
=> Use exit code 2 to indicate error

Cargo.toml, src/args.rs, src/main.rs, src/printer.rs, termcolor/src/lib.rs
This also uses a buffer for `--files` where it didn't previously, so this will likely speed that up too when there are many file paths to print.
=> use buffered writing for single threaded search

src/app.rs
Simple as this probably? I didn't add a test since i don't see any for other options like this, but let me know if you'd like one.
I also didn't update the completion function. I guess we need to decide whether it's useful to show all of the `--no-*` options; i'm leaning towards not usually. But i should add them as hidden options at least so that the exclusions are accurate. I'll do that eventually...
(Fixes #964)
=> Add --fixed-strings flag (fixes #964)

complete/_rg, src/app.rs, src/args.rs
The name of the `--maxdepth` option is inconsistent with all of the other `--max-*` options, and aside from being aesthetically displeasing it affects the ordering in the help output and completion results. I assume the wording `maxdepth` comes from `find`, and that makes sense on its own i guess, but... it just feels out of place to me here.
This PR changes the canonical name of the option to `max-depth`, leaving `maxdepth` as a hidden alias for backwards compatibility.
(I realise this is petty; feel free to just close if i'm being *too* ridiculous...)
=> Rename --maxdepth to --max-depth

ci/test_complete.sh, complete/_rg
I'd been meaning to update this, and i think it's in a state now where it's much better than it was.
I propose that we give this a few days to sit before merging, just to make sure i haven't messed anything up (it is a decent number of lines changed). It's been working for me so far in zsh 5.3 and 5.5, though. If any zsh users watching the repo care to test, that would be pretty cool.
Full details:
* I've updated the function to use spec grouping with `_arguments`. This makes it so much easier (IMO) to read and maintain option exclusions. The down side is that grouping is only available in zsh 5.4+ (released in 2017); on older versions of zsh i simply strip the groups out. This makes option exclusivity pretty inaccurate on those older versions, but i think it's worth it — it's not like it …
=> Improve zsh completion

complete/_rg
Complete `--no-pre` — and then break pre/zip options apart since not all of them should be exclusive.
(The CI script doesn't account for completion specs that are marked with a `!`, which is why the tests didn't break when `--no-pre` was added. I could change that, but i think my concern at the time was that those 'negatory' options wouldn't always show up in the usage help. idk, probably not a big deal either way)
=> complete: add --no-pre, improve --pre/--search-zip exclusivity

tests/tests.rs, tests/workdir.rs
tests: reduce reliance on state in tests
This commit improves the integration test setup by running tests inside
the system's temporary directory instead of within ripgrep's `target`
directory. The motivation here is to attempt to reduce the effect of
unanticipated state on ripgrep's integration tests, such as the presence
of `.gitignore` files in ripgrep's checkout directory hierarchy
(including parent directories).
This doesn't remove all possible state. For example, there's no
guarantee that the system's temporary directory isn't itself within a
git repository. Moreover, there may still be other ignore rules in the
directory tree that might impact test behavior. Fixing this seems
somewhat difficult. Conceptually, it seems like ripgrep should run each
test in its own `chroot`-like …
=> tests: reduce effect of state on integration tests

README.md
This commit updates the download link in Debian installation instructions to reflect the latest release.
=> Update Debian installation instructions by bumping version to 0.9.0

ignore/src/types.rs
This adds support for Idris, Dhall, and ATS to the `ignore` crate.
=> add Idris, Dhall, and ATS

ignore/src/types.rs
Sbt is currently most used Scala build tool which uses *.sbt files, which are basically Scala.
=> Add *.sbt to scala type

ci/test_complete.sh, complete/_rg, src/app.rs
As requested in #1017, here's a proper PR for the feedback i had regarding zsh completion, documentation typos, and a `--no-multiline-dotall` option
Thanks again
=> Completion changes, &c., in light of libripgrep

complete/_rg
As discussed in #1017 again — this adds a brief\* explanation of `_arguments` specifications to the zsh completion function, as a reference for other developers to use when making minor changes to the function. I mainly focussed on option specs, since that's the most common thing to change.
\* Not actually that brief, lol. Is it too wordy for a 'reference'? If you have suggestions as to how i could make it more 'skimmable' i'm definitely open to them. Or obv if you have any unanswered questions i can address them
ETA: Fixed very minor typo
=> Add zsh-completion reference guide

ignore/src/types.rs
I've personally never seen `.mao`, but GitHub includes it in Linguist: 
https://github.com/github/linguist/blob/4f11062304ae28b09a9b90c4536a92a27e142dcb/lib/linguist/languages.yml#L2702-L2709
=> ignore/types: add .mako and .mao for Mako templates

Cargo.lock, complete/_rg, ignore/Cargo.toml, ignore/src/lib.rs, ignore/src/walk.rs, src/app.rs, src/args.rs
Closes #321, Closes #404 
cc @okdana Mind checking if I got the completions right? If I got it this time, then I think I've grok'd it.
=> add --one-file-system, --sort and --sortr

complete/_rg
This should fix the issue you mentioned with the `rg -f` completion. Sorry about that
=> complete: don't complete bare pattern after -f

ignore/src/walk.rs
This commit adds `ignore::DirEntry::into_path` to match `walkdir::DirEntry`.
=> ignore: Add into_path for DirEntry

Cargo.toml
Put it in the same section as https://packages.debian.org/stretch/grep.
=> Add section info for deb package

Cargo.lock, grep-regex/src/literal.rs, grep-searcher/Cargo.toml, src/args.rs, tests/regression.rs
* Fixes #1052 (panic when searching Ruby source checkout)
* Fixes #1055 (suggest `-U/--multiline` when `\n` is used in pattern)
* Fixes #1064 (fix missing match for `a(.*c)`)
=> fix a few bugs

ignore/src/types.rs
BuildStream is a Free Software tool for building/integrating software stacks.: https://buildstream.gitlab.io/buildstream/
It uses recipes written in YAML, in files with the `.bst` extension.
---
I wonder about the name if the type. I used `buildstream` because that's the name of the project, but the command line is `bst` so that's another possible name.
The latter is also shorter, which is nice when using `rg --type=bst …`.
Do you have a policy on this? Can we add both?
=> Add Buildstream type

ignore/src/types.rs
This adds `"BUILD.bazel"` to the filename patterns for the `bazel` file type.
Bazel allows `BUILD.bazel` as a filename alternative to `BUILD`, see bazelbuild/bazel#4517 and the [0.4.1 release changelog](https://github.com/bazelbuild/bazel/blob/master/CHANGELOG.md#release-041-2016-11-21).
=> Add BUILD.bazel to bazel file type

ignore/src/types.rs
From the [Cython file types](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html?highlight=pxi#cython-file-types) paragraph on the official docs:
>There are three file types in Cython:
>   - The implementation files, carrying a .py or .pyx suffix.
>   - The definition files, carrying a .pxd suffix.
>   - The include files, carrying a .pxi suffix.
So I added `pxi` and `pxd` to the list. (In fact because `ripgrep` was not searching in all my cython files :smile:)
=> Add missing Cython file types

ignore/src/types.rs
Although postscript/encapsulated postscript is usually thought of as a
binary format, it's actually mostly ASCII, so ripgrep will not ignore
these files.
The situation is basically the same as for pdf, which is also already
present in the list of known filetypes.
=> Add postscript to known file types.

.travis.yml, Cargo.lock, Cargo.toml, globset/Cargo.toml, grep-cli/Cargo.toml, grep-matcher/Cargo.toml, grep-printer/Cargo.toml, grep-regex/Cargo.toml, grep-searcher/Cargo.toml, grep/Cargo.toml, ignore/Cargo.toml, src/app.rs, src/args.rs, src/config.rs, src/main.rs, src/messages.rs, src/search.rs, src/subject.rs, tests/feature.rs, tests/json.rs, tests/macros.rs, tests/misc.rs, tests/multiline.rs, tests/regression.rs, tests/tests.rs
This PR updates lots of dependencies such that I believe we are now fully up to date. We also bump the MSRV to the latest stable release (Rust 1.32) and migrate ripgrep core to Rust 2018.
=> bump dependencies and migrate core to Rust 2018

ignore/src/gitignore.rs
(This is kind of related to #762, but not exactly. The issue was present before that was merged. I don't think anyone's ever complained, though, because there's no test for it.)
In the `ignore` crate, there's a check for a literal `/` in `gitignore` patterns. If there is one, `literal_separator` is set to `true`, preventing `*` from matching slashes; if there's not, `*` is allowed to match slashes.
Whether the `*` matches slashes doesn't really matter either way for patterns like `*foo` and `foo*`, but it's pretty important for `foo*bar`. In that case (without `literal_separator`), the `gitignore` matcher will return a successful match for both `foobazbar` *and* `foo/baz/bar`.
Git itself does not seem to treat `gitignore` patterns like this (tested 2.17.1 and 2.19.1).
You can run the …
=> Fix inconsistent handling of gitignore patterns like foo*bar

src/args.rs
This looks basically equivalent to the earlier fix for #600
=> Fix #1121 - avoid triggering windows antimalware when in --files mode

ignore/src/types.rs
The --type tex should include documented LaTeX sources (.dtx) and their .ins files
=> *.dtx and *.ins added for -type tex

.travis.yml
Rust is having problems with trusty, in particular, see this bug I
filed: https://github.com/rust-lang/rust/issues/59411
This was purpotedly fixed in
https://github.com/rust-lang/rust/pull/59468,
but it appears the issue is still occurring.
This commit tries to update to Ubuntu 16.04 in the hope that it will fix
this problem.
=> ci: switch to xenial

Cargo.lock, Cargo.toml, GUIDE.md, doc/rg.1.txt.tpl, globset/Cargo.toml, globset/src/glob.rs, globset/src/lib.rs, globset/src/pathutil.rs, grep-cli/Cargo.toml, grep-cli/src/escape.rs, grep-cli/src/lib.rs, grep-printer/Cargo.toml, grep-printer/src/lib.rs, grep-printer/src/util.rs, grep-regex/src/config.rs, grep-regex/src/crlf.rs, grep-regex/src/literal.rs, grep-regex/src/matcher.rs, grep-regex/src/word.rs, grep-searcher/Cargo.toml, grep-searcher/src/lib.rs, grep-searcher/src/line_buffer.rs, grep-searcher/src/lines.rs, grep-searcher/src/searcher/core.rs, grep-searcher/src/testutil.rs, src/config.rs
This migrates a few of ripgrep's core crates to using byte strings, which let's us get rid of a fair bit of annoying platform specific code (and is now pushed down into `bstr`).
This PR also fixes a performance regression that occurs in some cases when `-w` is used. Namely, literal detection is thwarted in some cases.
=> partially migrate to using byte strings

src/args.rs
31d3e241306f305c1cb94e1882511da2b48dcd36 added this wrapper around the invocation of Clap which manually writes whatever output it produces. But it uses `writeln!()`, and Clap's output is already new-line-delimited, so `--help` and `--version` now have an extra new-line at the end that inexplicably upsets me. This just makes it go away again
=> Remove extra new-line after Clap output

README.md
This adds a badge to the README.md file indicating to users that click on it if their os/distro carries that latest version of ripgrep. The badge looks like this:  
[![Packaging status](https://repology.org/badge/tiny-repos/ripgrep.svg)](https://repology.org/project/ripgrep/badges)
Preview https://github.com/BurntSushi/ripgrep/blob/5cc12cba816e84a7884c755883cad0e3927d7187/README.md
=> README.md: Add Repology badge

ignore/src/types.rs
I keep running into this issue where i want to use `-tc` to search a repository, and i don't get everything i expect because some of the files are those `foo.h.in` ones. I know it's not feasible to support *every* possible `*.in` extension, but these are really common in C and C++ projects — for example, zsh and PCRE have a lot of them — so hopefully that justifies it...?
In doing this, i combined a bunch of patterns with `[...]` because it seemed like it'd be easier to maintain the `*.in` variants that way. Let me know if it makes it more confusing though
=> ignore/types: add *.am and *.in for C/C++/make

Cargo.lock, GUIDE.md, complete/_rg, grep-regex/src/matcher.rs, grep-searcher/Cargo.toml, grep-searcher/src/searcher/mod.rs, src/app.rs, src/args.rs, tests/feature.rs
This commit adds a new encoding feature where the -E/--encoding flag
will now accept a value of 'none'. When given this value, all encoding
related machinery is disabled and ripgrep will search the raw bytes of
the file, including the BOM if it's present.
Closes #1207, Closes #1208
=> searcher: add option to disable BOM sniffing

CHANGELOG.md, Cargo.lock, grep-regex/Cargo.toml, grep-regex/src/config.rs, grep-regex/src/crlf.rs, grep-regex/src/lib.rs, grep-regex/src/matcher.rs, grep-regex/src/multi.rs, grep-regex/src/word.rs, src/args.rs
This makes the case of searching for a dictionary of a very large number
of literals much much faster. (~10x or so.) In particular, we achieve this
by short-circuiting the construction of a full regex when we know we have
a simple alternation of literals. Building the regex for a large dictionary
(>100,000 literals) turns out to be quite slow, even if it internally will
dispatch to Aho-Corasick.
Even that isn't quite enough. It turns out that even *parsing* such a regex
is quite slow. So when the -F/--fixed-strings flag is set, we short
circuit regex parsing completely and jump straight to Aho-Corasick.
We aren't quite as fast as GNU grep here, but it's much closer (less than
2x slower).
In general, this is somewhat of a hack. In particular, it seems plausible
that this optimization could …
=> regex: make multi-literal searcher faster

ignore/src/types.rs
- `*.dtd` for Document Type Definitions
- `*.xsl` and `*.xslt` for XSL Transformation descriptions
- `*.xsd` for XML Schema definitions
- `*.xjb` for JAXB bindings
- `*.rng` for Relax NG files
- `*.sch` for Schematron files
=> Support for files for type `xml`

ignore/src/types.rs
Add support for file types used by the GAP language, a research system
computational discrete algebra, see <https://www.gap-system.org>
=> ignore/types: add GAP

README.md
This feature solves a major reason I was skeptical of using ripgrep, so I think it’s good to mention it in the section about why one should use it.
I use backreferences a lot, so I had previously thought that ripgrep would provide no speed advantage over ag, since I would always have `-P` enabled. But when I saw `--auto-hybrid-regex` in the [11.0.0 changelog](https://github.com/BurntSushi/ripgrep/blob/11.0.0/CHANGELOG.md#1100-2019-04-15), I learned that ripgrep can use it to speed up simple queries while still allowing me to write backreferences.
=> Mention `--auto-hybrid-regex` in the README’s advantages section

README.md
This is for consistency with the short and long flags given in other bullet points. I originally assumed there was no long flag for `-P` because none was given here.
=> readme: mention --pcre2 as long form of -P

README.md
Issue #10 already states that "ripgrep is now in most or all of the major
package repositories"
=> Remove outdated statement about rg in package repositories from readme

GUIDE.md
Cargo.toml says regex 1.0.5, and its doc is different, e.g. adds "symmetric differences" under https://docs.rs/regex/1.0.5/regex/#character-classes
=> Point regex doc link to the version ripgrep uses

src/app.rs
I ran into this issue today, so I thought it'd be nice to document it for others :smiley:
(I only noticed it because my shell highlights expanded variables thanks to [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting)…)
=> Document shell-specific caveats related to the `--replace` flag

ignore/src/types.rs
[Robot Framework](https://robotframework.org/) scripts and resource files have the file extension `.robot`
=> ignore/types: add Robot Framework

README.md
It seems that the Scoop buckets were moved to separate repositories: https://github.com/lukesampson/scoop/blob/master/buckets.json
=> readme: fix broken link to Scoop bucket

ignore/src/walk.rs
Currently the crate assumes that exactly one of `cfg(windows)` or
`cfg(unix)` is true, but this is not actually the case, for instance
when compiling for `wasm32`.
Implement the missing functions so that the crate can compile on other
platforms, even though those functions will always return an error.
=> Support compiling `ignore` crate to wasm32

complete/_rg, src/app.rs, src/args.rs, tests/misc.rs
Hopefully this is what you had in mind. The flag forces `-g`/`--glob` to be treated as `--iglob`.
If usability on case-insensitive file systems is a concern, i suppose the next logical request would be an option to make the built-in type patterns case-insensitive as well. But i didn't touch that obv
Fixes #1293
=> Add --glob-case-insensitive

README.md
Since 2019-07-06. The readme has been outdated for a month. https://www.debian.org/News/2019/20190706
=> Update README.md since Debian Buster is stable now

doc/rg.1.txt.tpl
This is a minor update to ripgrep's manpage to reflect the changes in #762. The manpage's use of `!git/*` in glob patten matching examples, which is presumably intended to exclude all `git` directories from ripgrep's search, is incorrect. This might be a source of confusion for people configuring ripgrep who may not be familiar with `.gitignore` semantics.
=> minor update to manpage to reflect glob matching behavior change

ignore/src/gitignore.rs
A couple of comments in ignore/src/gitignore.rs referenced "XDG_CONFIG_DIR", which isn't an XDG variable. I believe that "XDG_CONFIG_HOME" is what was meant.
=> reference XDG_CONFIG_HOME instead of incorrect XDG_CONFIG_DIR

.github/workflows/ci.yml
Since this workflow specifies `runs-on: ${{matrix.os}}`, the `os` parameter needs to be defined for every build run.
Even though `include` is defined just for `pinned-musl` and `stable`, the other `build`s will still run—`include` is just saying "when these parameters match existing jobs, include some additional ones".
I've also added `sudo` to your `apt-get` command here—when running steps directly on the VM (as opposed to Docker), you're not running as root, and so password-less sudo can be used where needed.
=> Ensure intended builds run

ignore/src/types.rs
I noticed the postscript globs were missing asterisks, so they were treated as literal filenames.
=> ignore/types: fix postscript globs

ignore/src/types.rs
This change maintains the existing behavior of the 'groovy' type, which includes both .groovy and .gradle files.
=> Make 'gradle' it's own explicit type.

ignore/src/types.rs
`.org_archive` is the default extension for Org archive files, created when
entries from an Org-mode file are archived (see
<https://orgmode.org/org.html#Moving-subtrees>). These files are still in Org
mode format, so it's worth searching them at the same time as non-archive Org
mode files.
=> Add *.org_archive to org file type

ignore/src/types.rs
Add the file types for TypoScript - the configuration language of the
TYPO3 CMS.
=> Add typoscript file type

ignore/src/types.rs
[Slim](http://slim-lang.com/) is a popular templating language for ruby, and [Slime](https://github.com/slime-lang/slime) is its elixir counterpart. [Skim](https://github.com/appjudo/skim) is "rails javascript" variant of it.
=> ignore/types: Add slim, slime, and skim template filetypes

README.md
ripgrep install instructions are valid even for the 7  version. The tool works without problems on these too.
=> Documented CentOS 8 support

README.md
Looks like the [upstream brew Formula][0] now has SIMD support, so
remove the extraneous info now that the custom tap [is no longer needed][1].
[0]: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ripgrep.rb
[1]: https://github.com/BurntSushi/ripgrep/commit/f3083e4574ad20881de66fdeb66d671f1cbdfda4
=> readme: remove outdated SIMD info

CHANGELOG.md, Cargo.lock, Cargo.toml, GUIDE.md, README.md, ci/test_complete.sh, complete/_rg, doc/rg.1.txt.tpl, globset/Cargo.toml, globset/src/glob.rs, grep-printer/src/summary.rs, grep-regex/Cargo.toml, grep-regex/src/literal.rs, grep-regex/src/matcher.rs, grep-regex/src/word.rs, ignore/Cargo.toml, ignore/src/dir.rs, ignore/src/lib.rs, ignore/src/types.rs, ignore/src/walk.rs, src/app.rs, src/args.rs, src/main.rs, tests/feature.rs, tests/misc.rs, tests/regression.rs, tests/util.rs
This PR merges a number of outstanding PRs. In many cases, I've added touched up PRs in order to merge them. (e.g., Writing commit messages, adding changelog entries, etc.)
=> giant rollup

crates/ignore/src/default_types.rs
Adds support for files used by the [K executable semantic framework](http://www.kframework.org/index.php/Main_Page); code [here](https://github.com/kframework/k).
=> ignore/types: add K type

Cargo.lock, crates/globset/Cargo.toml, crates/globset/README.md, crates/globset/src/lib.rs, crates/globset/src/serde_impl.rs
Closes #1455.
This PR adds an optional dependency to serde, which implies a matching feature named `serde`. When enabled, `Serialize` and `Deserialize` are implemented for `Glob`, using its string form.
Implementing serde traits for `GlobSet` might also be a good idea, but looked like it might be a much more invasive change.
I used serde_json for the included test. There might be other edge cases that should be tested.
=> globset: Implement serde::{Serialize, Deserialize} for Glob

crates/cli/Cargo.toml, crates/globset/Cargo.toml, crates/grep/Cargo.toml, crates/ignore/Cargo.toml, crates/matcher/Cargo.toml, crates/pcre2/Cargo.toml, crates/printer/Cargo.toml, crates/regex/Cargo.toml, crates/searcher/Cargo.toml
The homepage and repo urls for `ignore` and `globset` manifest keys weren't updated when the project structure changed, leading links from https://docs.rs and https://crates.io to 404s.
Sorry about the PR on the new globset repo, I happened to find it first before this crates directory.
=> update globset and ignore's cargo manifest urls

crates/ignore/src/default_types.rs
Add support for Gentoo's portage package manager spec files:
https://wiki.gentoo.org/wiki/Portage
Closes #1534
(N.B. Refiling #1534 since something seems borked about CI there. It keeps failing on being able to checkout the repo. Not sure if it's something to do with the forked repo, so trying it here.)
=> ignore/types: add ebuild type

crates/core/app.rs
Fix typo in the help description of the `-o` (`--only-matching`) flag.
=> cli: fix typo in help description

pkg/brew/ripgrep-bin.rb
Hello!
This will fix this currently happening error :
```
> brew install ripgrep-bin
==> Installing ripgrep-bin from burntsushi/ripgrep
==> Downloading https://github.com/BurntSushi/ripgrep/releases/download/12.0.0/ripgrep-12.0.0-x86_64-apple-darwin.tar.gz
Already downloaded: /Library/Caches/Homebrew/downloads/71ad3a51a074950abeaa875fb35ac00adca54d0852b0e0f4ed627056994fbecc--ripgrep-12.0.0-x86_64-apple-darwin.tar.gz
Error: An exception occurred within a child process:
ChecksumMismatchError: SHA256 mismatch
Expected: 59e78931a7577e76f40c937cae2782f2bbdcb40f056df5dd84247a671373525d
Actual: ebbc518ac019fc78b6429ec2e64b823c59b15a6f942436f43b9afc23c9aad9ea
Archive: /Library/Caches/Homebrew/downloads/71ad3a51a074950abeaa875fb35ac00adca54d0852b0e0f4ed627056994fbecc--ripgrep-12.0.0-x86_64-apple-da …
```
=> pkg: fix brew tap version to 12.0.1 to match sha

crates/ignore/Cargo.toml, crates/ignore/src/lib.rs, crates/ignore/src/walk.rs
This replaces the use of channels in the parallel directory traversal
with a simple stack. The primary motivation for this change is to reduce
peak memory usage. In particular, when using a channel (which is a
queue), we wind up visiting files in a breadth first fashion. Using a
stack switches us to a depth first traversal. While there are no real
intrinsic differences, depth first traversal generally tends to use less
memory because directory trees are more commonly wide than they are
deep.
In particular, the queue/stack size itself is not the only concern. In
one recent case documented in #1550, a user wanted to search all Rust
crates. The directory structure was shallow but extremely wide, with a
single directory containing all crates. This in turn results is in
descending into each of …
=> crates/ignore: switch to depth first traversal

crates/core/args.rs
It seems like `fn walker_parallel` in `core/args.rs` has a documentation copy/pasted from the `fn walker` above it.  Updated the documentation to be (IMO) more accurate.
It's my first contribution -- apologies if I'm not following some convention.
=> Update a misleading doc that may have originated from a bad copy/paste

crates/ignore/src/default_types.rs
Adding filetype for racket-lang (https://racket-lang.org/).
PS: Thanks for this awesome software!
=> ignore/types: add racket

crates/ignore/src/default_types.rs
VCL is the Varnish Configuration Language used by Varnish and Fastly.
https://varnish-cache.org/docs/trunk/users-guide/vcl.html
=> ignore/types: add vcl

crates/core/app.rs
The added wording reads a little redundant in the man page since the *AUTOMATIC FILTERING* section says basically the same thing. Not sure if that's a problem. But this should clarify the `--help` output at least?
Fixes #1703
=> doc: elaborate on the function of -u/--unrestricted

crates/ignore/src/default_types.rs
Well, I don't know Rust and the directory structure looks weird. Thought it would be hard to make the change, but `rg` told me I was wrong, `rg '\*.toml'` shows me exactly what I want. Thank you for this awesome tool!
This PR is for issue #1710
=> Add a type for minified files

crates/globset/Cargo.toml
I don't think globset requires Unicode support in regex for path matching (correct me if I'm wrong). I removed the dependency to make the crate lighter.
This won't affect the size of ripgrep, since it depends on Unicode in regex elsewhere. However, I've been meaning to use globset in [zoxide](https://github.com/ajeetdsouza/zoxide), and I'd like to keep the binary size as small as possible.
I tested a trivial program before and after the change, and the executable size went from 2544 KB to 2084 KB.
Thanks!
=> Remove regex unicode dependency from globset

crates/ignore/src/default_types.rs
Bazel supports `BUILD.bazel` as well as `WORKSPACE.bazel`. In
addition, it is common to ship BUILD/WORKSPACE templates for
external repositories suffixed with .bazel for easier tool
recognition.
=> Generalize bazel type to include *.bazel

crates/ignore/src/default_types.rs
This adds recognition of [Futhark](https://futhark-lang.org/) files.
Thanks! :)
=> Add Futhark recognition to ignore crate

.github/workflows/ci.yml, .github/workflows/release.yml, ci/utils.sh
Now that a new version of `cross` that includes the fix of https://github.com/rust-embedded/cross/issues/357 has been released (https://github.com/rust-embedded/cross/issues/359), we can resolve this FIXME.
=> ci: install cross from crates.io

crates/ignore/src/default_types.rs
YANG is described in RFC 6020
https://tools.ietf.org/html/rfc6020
=> Add yang file type

README.md
Small fix, updating the `.deb` link in the install commands. Also, a `.deb` can be installed using `apt install ./foo.deb`, should this be recommended instead?
=> README: installation: fix link to .deb

crates/ignore/src/lib.rs
`ignore::Error` wraps `std::io::Error` with additional information (as
well as expose non-IO errors).  For people wanting to inspect what the
error is, they have to recursively match the Enum.  Like with `is_io()`,
this provides `io_error` and `into_io_error` helpers to do this for
the user.  These are written to be consistent with `walkdir::Error`.
=> ignore: Provide IO Error

crates/ignore/src/default_types.rs
It's common to use `foo.BUILD` for the external workspaces `@foo` build files in bazel.
Example from pytorch https://github.com/pytorch/pytorch/blob/master/third_party/cpuinfo.BUILD
See more files like that in the same folder.
Also, add `*.bazelrc` pattern while we are here.
https://docs.bazel.build/versions/master/guide.html#bazelrc-the-bazel-configuration-file
The default one used by bazel is just plain `.bazelrc`, but it's common to use `user.bazelrc` and other named groupings and import them from the top-level one.
=> Add *.BUILD and *.bazelrc patterns to the default bazel type

ci/build-deb
If ripgrep hasn't been built yet (i.e. target/debug/ doesn't exist),
then cargo-out-dir can't find OUT_DIR and the copy commands fail. Fix by
running cargo build before finding OUT_DIR.
Also add a check to fail early with a sensible error message when
asciidoctor isn't installed, rather than failing because of a missing
rg.1 file after the build.
=> ci: fix deb build script in clean checkout

crates/searcher/src/line_buffer.rs
Looks like this was accidentally left set to 8 in commit 46fb77c.
=> Update outdated comment in line_buffer.rs

crates/core/app.rs
Fixes #1847
If you'd prefer to leave out the `--no-ignore-dot` part, I'm happy to update the PR accordingly
Thanks!
=> Update --hidden help section to define hidden

GUIDE.md
Updated formatting of nested list in file `GUIDE.md`
Github expects 4 spaces or a single tab before nested items inside list.
=> Updated formatting of nested list in GUIDE.md

crates/globset/src/serde_impl.rs
The bug was introduced during the migration to the 2018 edition
=> Fix compilation with serde feature enabled

crates/ignore/src/default_types.rs
Instead of Projectfile used shard.yml (since some years). Also add ecr, crystal template type.
=> Correct types for crystal

GUIDE.md
#607 is the top result for the search "ripgrep disable regex". I think it makes sense to add it to the user guide, since it's a very useful flag.
=> Add -F/--fixed-strings to the User Guide's Common options

crates/ignore/src/dir.rs
I've confirmed via strace that this eliminates a pile of stat calls.
=> If require_git is false, don't stat .git

crates/core/config.rs
close: #1990
```sh
$ RIPGREP_CONFIG_PATH=no_exist_path rg 'search regex'
no_exist_path: No such file or directory (os error 2)
```
```sh
$ RIPGREP_CONFIG_PATH=no_exist_path rg 'search regex'
failed to read the file specified in RIPGREP_CONFIG_PATH: no_exist_path: No such file or directory (os error 2)
```
=> Improve err msg when it fails to read the file specified in RIPGREP_CONFIG_PATH

crates/ignore/src/default_types.rs
Like .hpp, .hh is an occasionally used extension for C++ headers
(to distinguish them from C headers).
=> ignore/types: Add "*.hh" to headers

crates/ignore/src/default_types.rs
MODULE.bazel is a new file, and WORKSPACE.bazel was always supported
similar to BUILD.bazel vs BUILD.
=> Detect MODULE.bazel and WORKSPACE.bazel

crates/globset/Cargo.toml, crates/globset/src/lib.rs
As in the title. Would be nice to avoid the dependency (and the transitive dependency on `cfg-if`) when `log` isn't being used. Made it a default so logs remain when updating the crate.
As an aside, does the `simd-accel` feature do anything in `globset`?
=> globset: make 'log' an optional dep

crates/cli/src/human.rs
fix typo 'couldn't' in comment cli/src/human.rs
=> doc: fix typos in comment

.github/workflows/ci.yml, .github/workflows/release.yml
The actions-rs/toolchain project appears dead. dtolnay's also seems more
sustainable given its simplicity, but it does enough to suit our needs.
=> ci: switch to dtolnay/rust-toolchain

crates/core/app.rs
The documentation for both of these flag had "the the"; this PR changed them to "the".
=> Fix typos in byte-offset and colors

crates/ignore/src/default_types.rs
Adding support for Solidity as a language and the *.sol file extension corresponding to it. The idea is to allow for the use of the flag `--type solidity` in order to search only in Solidity files.
Solidity is a programming language for the Ethereum Virtual Machine and is one of the most popular languages for developing blockchain software.
https://soliditylang.org/about/
https://en.wikipedia.org/wiki/Solidity
Follow up to #2283. I'm not an experienced Rust dev and this is my first contribution to the repo so let me know if there are additional code locations to update or any other steps required for making a high-quality PR.
=> Add support for Solidity as a file extension

crates/ignore/src/default_types.rs
.epp files are getting more and more common in Puppet code bases so it
makes sense I think to include them as part of the "puppet" type.
https://puppet.com/docs/puppet/7/lang_template_epp.html
=> Add embedded puppet templates to the puppet type

crates/ignore/src/default_types.rs
[ReScript](https://rescript-lang.org/) is an OCaml-derived programming language that compiles to efficient and human-readable JavaaScript.
[ReasonML](https://reasonml.github.io/) is an alternative syntax for OCaml.
=> Add ReScript and ReasonML default types

crates/ignore/src/default_types.rs
After I accidentally mixed up the sorting in #2349 and didn't notice, I thought I'd add a test so hopefully the next time it happens to someone it can be caught before it's sent in as a PR.
=> ignore/types: add automated test for sortedness

crates/ignore/src/overrides.rs
I couldn't find a reason for this being intentional. `Clone` and `Debug` is also already implemented for `Override`, `Gitignore`, and `GitignoreBuilder`. But not for `OverrideBuilder`.
In my own project, I have a custom builder containing an `OverrideBuilder`, and would like to be able to add `Clone` to my builder.
=> Added Clone and Debug for OverrideBuilder

crates/ignore/src/default_types.rs
The default filter for terraform only checks for *.tf files, but there are quite few other terraform filetypes.
The explanation for all of them can be found below:
_(including a link to the documentation from Hashicorp at the time of writing)_
- [*.tf.json & *.tfvars.json is to capture the files written in JSON-based variant of the Terraform language](https://developer.hashicorp.com/terraform/language/files)
- [*.tfvars is used to supply variables](https://developer.hashicorp.com/terraform/cloud-docs/workspaces/variables#6-auto-tfvars-variable-files)
- [.terraform.lock.hcl is used as a Dependency lock file ](https://developer.hashicorp.com/terraform/language/files/dependency-lock
)
- [terraform.rc & .terraformrc, *.tfrc](https://developer.hashicorp.com/terraform/cli/config/config-file)
=> Enhance terraform default filter

crates/ignore/src/default_types.rs
.sln is the extension for Visual Studio Project Soltion files, one of the file types accepted as inputs by MSBuild.
I'm not sure if/how this kind of thing is tested, but I'd be happy to add a test if required.
=> ignore/types: add *.sln for msbuild

crates/ignore/src/default_types.rs
Default file is docker-compose.yml and the documentation mentions overrides in the form of docker-compose.*.yml
=> Add support for searching in Docker compose files

crates/core/app.rs
Small PR to improve the documentation around the --quiet flag.
Fixes https://github.com/BurntSushi/ripgrep/issues/1962
=> Improve documentation for quiet to make it clearer

crates/searcher/src/searcher/mmap.rs
memmap2 v0.3.0 introduced a [regression](https://github.com/RazrFalcon/memmap2-rs/commit/5e271224c8411c89b42060294f9393cfc7b12a2a) when trying to map files larger than 4GB on 32-bit architectures which was subsequently [fixed](https://github.com/RazrFalcon/memmap2-rs/commit/9aa838aed99a4879d8357ff295a0ca1c98ba1ae5) in v0.3.1.
This commit bumps locked version of the memmap2 dependency to the current v0.5.0 and reverts fdfc418be55ff91e0c2efad6a3e27db054cb5534 to re-enable mmap on 32-bit architectures as a different approach to fixing #1911.
This was tested to report matches from the end of a 5GB file using MinGW and Wine:
```
~/.wine/drive_c> wine rg.exe 3z5llj3n8b56dcpoj5aj4rlmq3bdpie wikidatawiki-20210901-pages-articles1.xml-p1p441397 --debug …
```
=> Re-enable mmap on 32-bit architectures

crates/ignore/src/default_types.rs
This PR adds `*.bat` and `*.cmd` file types.
In doing so, it makes a distinction between batch files (old standard from the MS-DOS era) and command scripts (new flavor - can operate on batch files, although `*.cmd` is preferred for various reasons, the main one being batch files will set `ERRORLEVEL` following inconsistent MS-DOS style rules).
=> ignore/types: add Windows Command Prompt files

CHANGELOG.md, crates/regex/src/word.rs, tests/regression.rs
It turns out our fast path for -w/--word-regexp wasn't quite correct in some cases. Namely, we use `(?m:^|\W)(<original-regex>)(?m:\W|$)` as the implementation of -w/--word-regexp since `\b(<original-regex>)\b` has some unintuitive results in certain cases, specifically when <original-regex> matches non-word characters at match boundaries.
The problem is that using this formulation means that you need to extract the capture group around <original-regex> to find the "real" match, since the surrounding (^|\W) and (\W|$) aren't part of the match. This is fine, but the capture group engine is usually slow, so we have a fast path where we try to deduce the correct match boundary after an initial match (before running capture groups). The problem is that doing this is rather tricky because it's …
=> regex: fix fast path for -w/--word-regexp flag

crates/globset/src/glob.rs
We currently implement globs by converting them to regexes, and in doing so, sometimes use grouping. In all but one case, we used non-capturing groups. But for alternations, we used capturing groups, which was likely just an oversight. We don't make use of capture groups at all, and while they usually don't have any overhead, they lead to weird cases like this one: https://github.com/rust-lang/regex/issues/1059
That particular issue is also a bug in the regex crate itself, which is fixed in https://github.com/rust-lang/regex/pull/1062. Note though that the bug fix in the regex crate is required. Even with this patch to globset, memory usage is reduced (by about half in rust-lang/regex#1059) but is not returned to where it was prior to the regex 1.9 release.
=> globset: use non-capture groups in regex transform

CHANGELOG.md, crates/ignore/src/default_types.rs
This PR extends Gradle file types with the following:
- Kotlin DSL buildscripts (`*.gradle.kts`)
- Gradle Java properties (`gradle.properties`)
- wrapper files (`gradle-wrapper.*`)
- wrapper scripts (`gradlew`, `gradlew.bat`)
=> ignore/types: tweak Gradle file types

CHANGELOG.md, crates/ignore/src/default_types.rs
- `.pl` is the most common extension in the wild, though `.pro` is preferred in places where file extension may clash with Perl[1]
- `.P` is used for compatibility with XSB Prolog dialect[2]
[1]: https://www.swi-prolog.org/pldoc/man?section=fileext
[2]: https://www.swi-prolog.org/pldoc/man?section=xsb-source
=> ignore/types: add Prolog file types

crates/ignore/src/default_types.rs
The V language (vlang.io) also uses *.vsh (V shell) as extension: https://github.com/vlang/v/blob/master/doc/docs.md#cross-platform-shell-scripts-in-v.
=> ignore/types: Add *.vsh to V type

CHANGELOG.md, Cargo.lock, crates/ignore/Cargo.toml, crates/ignore/src/dir.rs, crates/ignore/src/walk.rs, tests/regression.rs
This clears everything out of the PR queue except for hyperlink support.
=> rollup: filtering in subdirectories + work-stealing stack for parallel directory traversal

crates/ignore/src/default_types.rs
[SARIF][] is a format for reporting static analysis results. It is [used by GitHub CodeQL][GH] for example.
Here are some samples from Microsoft's VSCode extension:
https://github.com/microsoft/sarif-vscode-extension/tree/main/samples
The SARIF format is built on top of JSON. This PR associates `*.sarif` files with JSON.
[SARIF]: https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html
[GH]: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning
=> ignore/types: Add *.sarif for SARIF format files

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, Cargo.lock, FAQ.md, ci/build-and-publish-deb, ci/build-and-publish-m2, ci/docker/README.md, ci/macos-install-packages, ci/ubuntu-install-packages, crates/core/flags/complete/rg.zsh, crates/core/flags/defs.rs, crates/core/flags/hiargs.rs, crates/ignore/src/walk.rs, crates/printer/Cargo.toml, crates/printer/src/jsont.rs, crates/printer/src/stats.rs, crates/printer/src/util.rs
Most of this PR is focused on dropping dependencies that are probably not carrying their weight. This gets us back down to the size of the dependency tree in `ripgrep 0.3.2`, but the compile times are still a couple seconds slower for a clean release build (without PCRE2).
At this point, `cargo build --release --timings` on a clean build suggests that the biggest contributor to compile time is `regex-automata`. That's no surprise.
=> rollup PR queue + drop asciidoc/asciidoctor + drop serde_derive + drop base64

CHANGELOG.md, GUIDE.md, README.md, crates/core/flags/defs.rs, crates/core/flags/doc/template.long.help, crates/core/flags/doc/template.rg.1, crates/core/flags/doc/template.short.help, crates/core/flags/doc/version.rs, crates/core/flags/hiargs.rs, crates/core/flags/mod.rs, crates/core/main.rs, crates/printer/src/json.rs, crates/printer/src/standard.rs, crates/printer/src/summary.rs, crates/printer/src/util.rs, crates/regex/src/ban.rs, crates/regex/src/config.rs, crates/regex/src/error.rs, crates/regex/src/lib.rs, crates/regex/src/matcher.rs, crates/searcher/src/line_buffer.rs, crates/searcher/src/searcher/mod.rs, tests/feature.rs, tests/regression.rs
This is basically me trying to go through all of the issues knocking off relatively low hanging fruit.
=> rollup issue triage

crates/ignore/src/default_types.rs
Starting with meson 1.1, there is a preference for using meson.options
instead of meson_options.txt.  Add the new filename to the meson set.
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
=> ignore: meson: add meson.options

README.md
`guix install` should not be run using `sudo`, as per <https://packages.guix.gnu.org/packages/ripgrep/>.
Guix is more like Nix in that users install packages without root privileges.
=> Fix Guix install instructions

CHANGELOG.md, crates/core/flags/complete/encodings.sh, crates/core/flags/complete/fish.rs, crates/core/flags/complete/mod.rs, crates/core/flags/complete/rg.zsh, crates/core/flags/complete/zsh.rs, crates/core/flags/defs.rs, crates/core/flags/mod.rs
- Stop using `-n __fish_use_subcommand`. This had the effect of ignoring options if a positional argument has already been given, but that's not how ripgrep works.
- Only suggest negation options if the option they're negating is passed (e.g., only complete `--no-pcre2` if `--pcre2` is present). The zsh completions already do this.
- Take into account whether an option takes an argument. If an option is not a switch then it won't suggest further options until the argument is given, e.g. `-C<tab>` won't suggest options but `-i<tab>` will.
- Suggest correct arguments for options. We already completed a fixed set of choices where available, but now we go further:
- Filenames are only suggested for options that take filenames.
- `--pre` and `--hostname-bin` suggest binaries from `$PATH`.
- …
=> complete/fish: Make fish completion more intelligent

CHANGELOG.md, crates/ignore/src/dir.rs
This attempts to fix the issue around unbounded memory growth in the ignore crate when ignore flags are enabled, see https://github.com/BurntSushi/ripgrep/issues/2690
I don't have full understanding of the ignore crate codebase but it looks like there is a reference cycle caused by the compiled matchers (compiled HashMap holds ref to Ignore and Ignore holds ref to HashMap). Using weak refs fixes issue #2690 in my test project. Also confirmed via before and after when profiling the code, see the attached screenshots.
=> ignore crate: Fix reference cycle for compiled matchers

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, crates/core/flags/doc/version.rs, crates/grep/Cargo.toml, crates/searcher/Cargo.toml
This feature causes nothing but problems and is frequently broken. The
only optimization it was enabling were SIMD optimizations for
transcoding. In particular, for UTF-16 transcoding. This is performed by
the [`encoding_rs`](https://github.com/hsivonen/encoding_rs) crate,
which specifically uses unstable portable SIMD APIs instead of the
stable non-portable SIMD APIs.
SIMD optimizations that apply to search have long been making use of
stable APIs, and are automatically enabled when your target supports
them. This is, IMO, the correct user experience and one that
`encoding_rs` refuses to support. I'm done dealing with it, so
transcoding will only use scalar code until the SIMD optimizations in
`encoding_rs` work on stable. (This doesn't mean that `encoding_rs` has
to change. This could …
=> cargo: nuke 'simd-accel' from orbit

crates/ignore/src/default_types.rs
Added svelte filetype as default filetype, ran `cargo test -all` to confirm tests worked Ran `rg --type-list` to convert svelte showed up
=> feat: add svelte file types as default filetype

crates/ignore/src/walk.rs
The returned closure should return `WalkState`, not `()`.
Closes: #2767
=> ignore/walk: correct build_parallel() documentation

crates/ignore/src/default_types.rs
[WGSL][1] is a shading language for WebGPU. As defined in [Appendix A][2], the file extension is `.wgsl`.
This PR adds a file type support for WGSL to ripgrep.
[1]: https://www.w3.org/TR/WGSL/
[2]: https://www.w3.org/TR/WGSL/#text-wgsl-media-type
=> ignore/types: add WGSL to the default file types

.github/workflows/ci.yml, crates/cli/src/hostname.rs, crates/printer/src/hyperlink.rs
The code of ripgrep compiles on almost any kind of architecture, including WebAssembly, except in two tiny places related to hyperlinks: 
- when it searches for the local hostname in `hostname.rs`, 
- when it does path canonalization in `hyperlink.rs`.
In both cases, there is a path with `#[cfg(unix)]` and a path with `#[cfg(windows)]`. WebAssembly being neither unix nor windows, compilation fails. This PR adds a third path:
- for localhost, it returns "localhost" instead of calling `gethostname()`, for all environments that are neither unix nor windows.
- for path canonalization, it uses `std::os::wasi::ffi::OsStrExt` instead of `std::os::unix::ffi::OsStrExt`, which is not available; this part is specific for wasm32-wasi. It could be possible to deactivate path canonalization entirely …
=> Set up ripgrep for compilation on non-unix, non-windows platforms

crates/core/flags/defs.rs
I found a very small typo in the help message and I thought might as well fix it
=> fix: typo in vimgrep help message

README.md
`ripgrep` is available to install through the [Flox CLI](https://flox.dev/docs/), and seems to be working today.
Since Nix, and Guix, are also listed as installation option, I thought Flox might make sense as well.
=> Add Flox as an installation method

README.md
FINALLY FIXED IT! idk if I did it right but let me know if this is okay, I'd love to help you out more if you want!!
=> Update README.md to add the updated link for debian installation

crates/globset/src/glob.rs
Rewrites the `char_to_escaped_literal` and `bytes_to_escaped_literal` functions in a way that minimizes heap allocations.
After this, the resulting string is the only allocation remaining.
=> Optimize character escaping.

README.md
It seems the entry for ugrep in this table was copied-and-not-updated from the previous table. The timing measurements indicate that the correct command was measured, so I considered this the most likely command that was used.
I'm unable to be 100% sure obviously.
=> Fix README typo in ugrep command for searches without literal optimization opportunities

crates/regex/src/literal.rs, tests/util.rs
In some rare cases, it was possible for ripgrep's inner literal detector
to extract a set of literals that could produce a false negative. #2884
gives an example: `(?i:e.x|ex)`. In this case, the set extracted can be
discovered by running `rg '(?i:e.x|ex) --trace`:
Seq[E("EX"), E("Ex"), E("eX"), E("ex")]
This extraction leads to building a multi-substring matcher for `EX`,
`Ex`, `eX` and `ex`. Searching the haystack `e-x` produces no match,
and thus, ripgrep shows no matches. But the regex `(?i:e.x|ex)` matches
`e-x`.
The issue at play here was that when two extracted literal sequences
were unioned, we were correctly unioning their "prefix" attribute.
And this in turn leads to those literal sequences being combined
incorrectly via cross product. This case in particular triggers it
because …
=> regex: fix inner literal extraction that resulted in false negatives

FAQ.md, crates/core/flags/complete/rg.zsh
Summary:
Previously, you needed to save the completion script to a file and then
source it.  Now, you can dynamically source completions in zsh by
running
```zsh
$ source <(rg --generate complete-zsh)
```
Test plan:
1. Run `source <(rg --generate complete-zsh)`
2. Run `rg --generate=complete-zs<TAB>`
Before this commit, you would get an error after step 1.
After this commit, it should work as expected.
Closes #2956
=> feat(completion): support sourcing zsh completion dynamically

.github/workflows/ci.yml
For more info visit the official rust [blog](https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html).
=> Fix the CI workflow broken by WASI compilation target rename

crates/globset/src/lib.rs
This appears to be an oversight from when `escape` was
implemented in #2061.
=> globset: escape `{` and `}` in `escape`

.github/workflows/ci.yml, Cargo.toml, README.md
This is to prep for the next release. I don't know if the requirement
will actually be for Rust 1.88, but it is intended to support the latest
version of stable Rust.
=> msrv: bump to Rust 1.88

README.md
I've split the previously singular "CentOS/RHEL/Rocky" section into 3
sections. They each benefit from having their own steps.
I've also copied steps from [EPEL Getting Started] documentation,
including steps that don't seem to be required because it seems to be
best practice (although I do not understand it). Notably, this is not
required for CentOS Stream:
```
dnf config-manager --set-enabled crb
```
And this is not required for Red Hat:
```
subscription-manager repos --enable codeready-builder-for-rhel-10-$(arch)-rpms
```
And neither are available on Rocky Linux 10. Hence, all 3 have slightly
different instructions.
It has been suggested (see [here][suggest1] and [here][suggest2]) that
the installation instructions should just link to the [EPEL Getting
Started] documentation and just …
=> doc: update the CentOS, RHEL and Rocky Linux installation instructions
