- README.md
The README should reflect that.
> ripgrep is now in [community]

- doc/rg.1
- doc/rg.1.md
- src/args.rs
> clarify docs for --threads

- src/types.rs
Tested locally and it works 👍 
Closes #171
> Add `handlebars` type

- README.md
> Use svg for travis badge

- ignore/src/types.rs
> adding .mak extension for makefile filetype.

- ignore/src/dir.rs
- ignore/src/lib.rs
These changes makes the code more readable in my opinion.
> `Ignore` refactorings

- ignore/src/types.rs
Seeing as #246 was added, it'd be a shame if the last big dialect wasn't included as well 😄
> Add stylus type

- Cargo.lock
- Cargo.toml
- src/app.rs
- tests/tests.rs
> Fix leading hypen bug by updating clap.

- src/args.rs
- src/pathutil.rs
- src/printer.rs
- src/search_buffer.rs
- src/search_stream.rs
- src/unescape.rs
- src/worker.rs
Fixes a few lints suggested by clippy.
> Fix some clippy lints

- ignore/src/types.rs
SWIG from http://swig.org/
Fixes #296
> Add types for handling SWIG files.

- termcolor/src/lib.rs
Currently, Rust's standard library will yield an error if one tries to
write invalid UTF-8 to a Windows console. This is problematic for
ripgrep when it tries to print matched lines that contain invalid UTF-8.
We work around this by modifying the `termcolor` library to lossily
decode UTF-8 before sending it to `std::io::Stdout`. This may result in
some Unicode replacement chars being shown in the output, but this is
strictly better than erroring or not showing anything at all.
Fixes #318.
> Fix invalid UTF-8 output on Windows.

- wincolor/src/win.rs
Might as well get this bit in — hopefully this one isn't controversial?
> Add stderr support to wincolor.

- ignore/src/types.rs
Ceylon is from here: https://ceylon-lang.org.
> Add Ceylon file type filtering

- ignore/src/types.rs
Add twig filetype for http://twig.sensiolabs.org/
> Add .twig as a Filetype

- globset/src/glob.rs
- tests/tests.rs
> Add enclosing group to alternations in globs

- doc/rg.1.md
- src/app.rs
- tests/tests.rs
> Add -0 shortcut for --null #419

- Cargo.lock
> Bump clap version

- src/search_buffer.rs
See, some people actually read comments ;)
> fix typo in comment

- README.md
Updated the readme with tips on piping non-ASCII content (the cause/fix for https://github.com/BurntSushi/ripgrep/issues/471) and on resetting colors after `ctrl+c` in Powershell (because `color` isn't supported), plus instructions for using the Powershell autocompletion file (which is dependent on ripgrep updating to clap 2.23.2, see https://github.com/BurntSushi/ripgrep/issues/445 and https://github.com/kbknapp/clap-rs/issues/931).
> Add Powershell tips and autocompletion instructions

- ignore/src/types.rs
Here is a PR for supporting QMake (from Qt) files :)
> Add support for QMake files

- doc/rg.1
- doc/rg.1.md
> Fix typo, should be 'mode' instead of 'more'

- README.md
- build.rs
- ci/before_deploy.sh
- complete/_rg
clap-rs [1] does not generate good Zsh completion files, thus a custom completion script should be better.
I have refined https://github.com/zsh-users/zsh-completions/pull/510 and added more options to `complete/_rg`.
[1]: https://github.com/kbknapp/clap-rs/issues/868
> Add custom Zsh completion file

- ignore/src/types.rs
> Add a cshtml ignore type

- ignore/src/types.rs
This PR adds support for [julia](https://github.com/JuliaLang/julia) files
> Add julia as file type

- ignore/src/types.rs
add file types for embedded linux Yocto project : https://www.yoctoproject.org/
> add yocto file types

- ignore/src/gitignore.rs
- ignore/src/overrides.rs
- src/app.rs
- src/args.rs
- tests/tests.rs
Working with Chris Stadler, implemented
https://github.com/BurntSushi/ripgrep/issues/163#issuecomment-300012592
This addresses #163
> add --iglob flag

- complete/_rg
In light of #531 getting merged
> Add --iglob to zsh completion function

- complete/_rg
- doc/rg.1
- doc/rg.1.md
- src/app.rs
> doc: clarify --with-filename behavior with --heading

- ignore/src/types.rs
This is to address #609.
I've not worked with Rust before, so please kindly let me know if there are things I'm missing.
> add support for terraform file type

- README.md
Minor wording/formatting change which hopefully addresses the concerns of @niftylettuce in #618
> Update README to be more explicit about precompiled binaries (fixes #618)

- README.md
Mentioned it in the README file :)
> Ripgrep installs from Linuxbrew just fine and works as expected

- README.md
Should address the alias issue mentioned in #637, and maybe a few others
> Add troubleshooting notes re: conflicting tools/aliases (fixes #637)

- doc/rg.1
- doc/rg.1.md
- src/app.rs
I simple documentation update to state the default case sensitivity.
> State the default case sensitivity

- README.md
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
---
@BurntSushi ugh, now I finally understood what you were talking about! Sorry!
> remove reference to copr for F28+

- Cargo.lock
- Cargo.toml
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> deps: update bytecount to 0.3

- ignore/src/types.rs
Fixes #747
Why *not* invent your own data-serialisation format?
🤷‍♀️
> yarn.lock is not YAML

- ignore/src/types.rs
> types: add webidl (*.webidl)

- ignore/src/types.rs
Used by Prestashop CMS and more.
> Add Smarty tpl extension support

- .travis.yml
- ci/script.sh
- ci/utils.sh
This modifies CI to check that we generate completion files and a man
page.
We also enable tests on arm.
> ci: test build outputs

- README.md
This is the official markdown snippet from shields.io
> Update Crates.io badge

- GUIDE.md
- doc/rg.1.txt.tpl
As discussed in https://github.com/BurntSushi/ripgrep/issues/927#issuecomment-391888676
> Syncing examples between guide & man page

- ignore/src/types.rs
FIDL is the Fuchsia Interface Definition Language
https://fuchsia.googlesource.com/zircon/+/HEAD/docs/fidl/index.md
> Added FIDL type

- Cargo.lock
- Cargo.toml
This is one of the steps needed to be able to merge https://github.com/rust-lang/rust/pull/52972
> update bytecount dependency

- src/app.rs
By the way: thanks for making ripgrep, it's a really great tool!
> Fix typo: "cretion" -> "creation"

- ignore/src/types.rs
Adds support for the various filetypes that ASP code uses.
> Add support for ASP filetypes

- src/app.rs
> doc: fix typo

- ignore/src/types.rs
http://doc.qt.io/qt-5/qmlreference.html
> Add support for QML filetypes

- ignore/src/types.rs
> Add support for Zig (*.zig) files

- README.md
(Also alphabetise the list.)
(Was just reading the readme and was surprised Zstandard wasn't supported, but turned out it is, hence thought the update was worthwhile :-) )
> Mention Zstandard and Brotli in README

- ignore/src/types.rs
Add nim build configuration (.nimble) and code filtering (.nimf) file types.
> Additional nim filetypes [feature]

- .github/workflows/ci.yml
- Cargo.lock
- Cross.toml
- ci/docker/x86_64-unknown-linux-musl/Dockerfile
- ci/utils.sh
- grep-printer/Cargo.toml
- grep-regex/Cargo.toml
- grep-regex/src/word.rs
- grep-searcher/Cargo.toml
- ignore/Cargo.toml
- ignore/src/gitignore.rs
- ignore/src/types.rs
This updates all possible dependencies.
Closes #1427
> house cleaning and dependency updates

- GUIDE.md
Just a small typo fix. Thanks for this fantastic tool and the thorough user guide!
> Add missing "will" to GUIDE.md

- .github/workflows/ci.yml
This fix CI build as discussed in https://github.com/BurntSushi/ripgrep/pull/1499
> ci: fix ci by removing fetch-depth 1

- crates/ignore/src/default_types.rs
Add the file type for the Coq proof assistant.
> Add coq file type

- crates/ignore/src/default_types.rs
> default_types.rs: Add meson filetype

- crates/ignore/src/default_types.rs
Provide support for DVC files (https://dvc.org/).
> Add dvc file type

- crates/ignore/src/default_types.rs
For google flatbuffers schema format: https://google.github.io/flatbuffers/
> Add .fbs (flatbuffers) type.

- FAQ.md
Thanks for the excellent tool!
> Add missing backtick in FAQ.md

- .gitignore
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
> Fix/Ignore HTML output of -Z timings

- README.md
At the moment I have only finished translating the README.md, but I plan to finish the rest this weekend.
> 📝 Add Spanish Translation

- crates/ignore/src/default_types.rs
> ignore/types: add po

- crates/ignore/src/default_types.rs
- https://stackoverflow.com/questions/55072891/what-is-this-file-config-ru-and-what-is-it-for
- https://fileinfo.com/extension/rbw
> Add config.ru and *.rbw to --type ruby

- crates/core/app.rs
Found this while figuring out how to word a similar flag. ;)
> doc: fix typo in --glob flag docs

- crates/ignore/src/default_types.rs
https://www.gnu.org/software/texinfo/
> Add support for texinfo files

- crates/ignore/src/default_types.rs
> ignore/types: add fennel

- GUIDE.md
Even if transcoding would be faster than search it would still incur performance penalty
> transcoding is done in addition to search

- crates/cli/Cargo.toml
- crates/globset/Cargo.toml
- crates/grep/Cargo.toml
- crates/ignore/Cargo.toml
- crates/matcher/Cargo.toml
- crates/pcre2/Cargo.toml
- crates/printer/Cargo.toml
- crates/regex/Cargo.toml
- crates/searcher/Cargo.toml
Followup to d11a3b33773620bcc593f82b557757f0c2ec8a05.
> Use SPDX license format

- GUIDE.md
add -. short flag as with the others flags
> Update GUIDE to show hidden short flag

- crates/ignore/src/default_types.rs
candid: https://internetcomputer.org/docs/current/developer-docs/build/candid/candid-concepts
motoko: https://internetcomputer.org/docs/current/developer-docs/build/cdks/motoko-dfinity/motoko/
> ignore/types: add motoko and candid

- crates/ignore/src/default_types.rs
See: https://github.com/carp-lang/Carp
>  ignore/types: add carp

- README.md
> readme: add guix installation instructions

- crates/ignore/src/default_types.rs
See: https://www.devicetree.org/
> ignore/types: add dts filetype

- crates/ignore/src/default_types.rs
https://peps.python.org/pep-0484/#stub-files
> ignore/types: add `*.pyi` for py

- crates/globset/src/serde_impl.rs
I am interested in putting GlobSet as a field of a configuration file in https://github.com/facebookincubator/reindeer.
```rust
#[derive(Deserialize)]
pub struct Fixup {
pub extra_srcs: GlobSet,
}
```
> impl Deserialize for GlobSet

- crates/ignore/src/default_types.rs
Supports the .NET C# Project file extension
> Adds .csproj to default_types.rs

- README.md
> readme: update benchmarks

- README.md
Playground mentioned in the readme as discussed in #2758.
> doc: playground (#2758)

- crates/ignore/src/default_types.rs
Support vue for *.vue files only
> ignore/types: add Vue type

- crates/cli/src/lib.rs
Stdin heuristic detection is complicated and opaque enough that it's
worth having easy access to the complete story that leads ripgrep to
decide whether to search stdin or not.
Ref #2806
> cli: add more logging for stdin heuristic detection

- crates/ignore/src/default_types.rs
For more info on the Seed7 programming Language see:
- on Wikipedia: https://en.wikipedia.org/wiki/Seed7
- Seed7 home:   https://seed7.sourceforge.net/
- Seed7 repo:   https://github.com/ThomasMertes/seed7
> Add support for Seed7 files

- crates/ignore/src/default_types.rs
... murphy's law never fails...  Sorry for that.
> Fix Seed7 file extension: .s7d -> .sd7
